In [1]:
import sys
sys.path.append('..')
import importlib
import neural_policies
import main
import game_utils
import policy_gradient

import torch
import yaml
import numpy as np
import pyspiel
from types import SimpleNamespace

importlib.reload(main)
importlib.reload(neural_policies)
importlib.reload(game_utils)
importlib.reload(policy_gradient)

seed = 1
torch.random.manual_seed(seed)
np.random.seed(seed)

In [2]:
# game = game_utils.create_random_normal_game(5)
# game = main.create_game(SimpleNamespace(game="rps"))
game = main.create_game(SimpleNamespace(game="kuhn_poker"))
# nn_config_file = "../config/linear_mlp.yaml"
# nn_config_file = "../config/kuhn_mlp.yaml"
nn_config_file = "../config/kuhn_big.yaml"
reinforce_config_file = "../config/reinforce_train.yaml"
nn_config = yaml.safe_load(open(nn_config_file, "r"))
reinforce_config = yaml.safe_load(open(reinforce_config_file, "r"))

In [3]:
nash_policy, nash_value = main.nash_equilibrium_policy_and_value(game)
print("nash value", nash_value)
nn_player = 0
nn_policy = neural_policies.create_policy_net(game, nn_config)
nn_tab_policy = neural_policies.nn_to_tabular_policy(game, nn_policy, nn_player)

Exploitability: 0.06869879381715754
nash value [-0.05311271  0.05311271]


# ignore from here

In [4]:
# s = game_utils.all_game_states(game, 0)[0]
# s.legal_actions_mask()
# s.information_state_tensor()

In [5]:
from policy_gradient import PolicyGradientHypernetTrainer

# hypernet = main.train_hypernet_actionoutput(game, nn_config, nn_player, nn_policy, "../config/hypernet.yaml", "../config/hypernet_reinforce_train.yaml")

hypernet_config = "../config/hypernet.yaml"
hypernet_config = yaml.safe_load(open(hypernet_config, "r"))
hypernet_train_config = "../config/hypernet_reinforce_train.yaml"
hypernet_train_config = yaml.safe_load(open(hypernet_train_config, "r"))

mlp = neural_policies.create_policy_net(game, nn_config)
# hypernet = neural_policies.create_hypernet_nn_output(game, mlp, hypernet_config)
hypernet = neural_policies.create_hypernet_actionoutput(game, mlp, hypernet_config)
trainer = PolicyGradientHypernetTrainer(game, hypernet, hypernet_train_config)

  0%|          | 0/100000 [00:00<?, ?it/s]


AttributeError: 'HyperNetworkActionOutput' object has no attribute 'model_weight_output'

In [6]:
trainer.train_best_response(nn_config, 1 - nn_player)

  0%|          | 217/100000 [02:48<25:32:10,  1.09it/s]

[[0.67881411 0.32118592]
 [0.01395872 0.98604125]
 [0.64661425 0.35338572]
 [0.38737103 0.61262906]
 [0.763515   0.23648497]
 [0.68917471 0.31082529]
 [0.5        0.5       ]
 [0.5        0.5       ]
 [0.5        0.5       ]
 [0.5        0.5       ]
 [0.5        0.5       ]
 [0.5        0.5       ]]
[[0.5 0.5]
 [0.5 0.5]
 [0.5 0.5]
 [0.5 0.5]
 [0.5 0.5]
 [0.5 0.5]
 [0.  1. ]
 [0.  1. ]
 [0.  1. ]
 [0.  1. ]
 [0.  1. ]
 [1.  0. ]]
value of table br policy [-0.70484179  0.70484179]
[[5.00000000e-01 5.00000000e-01]
 [5.00000000e-01 5.00000000e-01]
 [5.00000000e-01 5.00000000e-01]
 [5.00000000e-01 5.00000000e-01]
 [5.00000000e-01 5.00000000e-01]
 [5.00000000e-01 5.00000000e-01]
 [7.79365229e-24 1.00000000e+00]
 [2.26749266e-25 1.00000000e+00]
 [3.91736507e-01 6.08263493e-01]
 [6.25857541e-25 1.00000000e+00]
 [5.27535791e-25 1.00000000e+00]
 [2.37434585e-25 1.00000000e+00]]
value of hypernet br policy [-0.53696586  0.53696586]
(0.0, 1.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0) -10.0 -6

  0%|          | 313/100000 [05:14<27:52:03,  1.01s/it] 


KeyboardInterrupt: 

In [6]:
nn_policy = neural_policies.create_policy_net(game, nn_config)
nn_tab_policy = neural_policies.nn_to_tabular_policy(game, nn_policy, nn_player)
main.tabular_br(game, nn_player, nn_tab_policy)
main.policy_gradient_br(
    game, nn_config, reinforce_config, nn_player, nn_policy, nn_tab_policy
)
main.hypernet_br(game, hypernet, nn_player, nn_policy, nn_tab_policy)

lst_policy = None

nn policy with tabular br value [-0.1596228  0.1596228]
value of nn br policy [-0.15929753  0.15929753]
value of hypernet br policy [-0.04876066  0.04876066]


In [7]:
# print(game.row_utilities())

new_input_nn = neural_policies.create_policy_net(game, nn_config)
input_probs = neural_policies.nn_to_tabular_policy(game, new_input_nn, nn_player).action_probability_array
# input_probs = neural_policies.get_nn_probs(new_input_nn, game.new_initial_state(), nn_player)
# print("input probs", input_probs)

playable_states = game_utils.all_game_states(game, 1-nn_player)
state = playable_states[0]

# print(neural_policies.get_hypernet_probs(hypernet, new_input_nn, state, 1-nn_player))
# print(hypernet(new_input_nn, torch.tensor(state.information_state_tensor(1-nn_player))))
nn_response = neural_policies.nn_to_tabular_policy(game, hypernet, 1-nn_player, new_input_nn)
# print("nn response", nn_response.action_probability_array)
br = main.compute_best_response_tabular_policy(game, nn_tab_policy, 1 - nn_player)
print(lst_policy)
if lst_policy is not None:
    cur_policy = br.action_probability_array
    # find rows that differ
    diff = np.where(cur_policy != lst_policy)
    print("diff", diff)
lst_policy = br.action_probability_array
print(br.action_probability_array)

# neural_br_policy = neural_policies.create_policy_net(game, nn_config)
# trainer = policy_gradient.PolicyGradientTrainer(
#     game, neural_br_policy, train_params=reinforce_config
# )
# trainer.train_best_response(nn_policy, 1-nn_player)
# print(neural_br_policy(torch.tensor(game.new_initial_state().information_state_tensor(1-nn_player))))
# print(neural_policies.get_nn_probs(neural_br_policy, game.new_initial_state(), 1-nn_player))

None
[[0.33333333 0.33333333 0.33333333]
 [1.         0.         0.        ]]


In [ ]:
from pprint import pprint
# pprint(list(hypernet._model.get_weights()))
mm = hypernet._model
[l.bias for l in mm.layers]
# mm.layers[-1].weight

In [7]:
import input_net_data
importlib.reload(input_net_data)
# input_nets = input_net_data.read_all_nn(game, "../nn_inputs/kuhn")
input_nets = input_net_data.read_all_nn(game, "../nn_inputs/kuhn-0-big")
# input_nets = input_net_data.read_all_nn(game, "../nn_inputs/rps")

In [8]:
ind = -1
nn_player

0

In [51]:
# nn_policy = neural_policies.create_policy_net(game, nn_config)
ind = ind + 1
# import random
# ind = random.choice([i for i in range(5)])
ind = ind % 5
print("ind", ind)
# print(input_nets[ind].get_weights())
nn_tab_policy = neural_policies.nn_to_tabular_policy(game, input_nets[ind], 0)
# br_pol = main.tabular_br(game, nn_player, nn_tab_policy)
print(nn_tab_policy.action_probability_array)

# print(nn_tab_policy.action_probability_array)

br = main.compute_best_response_tabular_policy(game, nn_tab_policy, 1)
print(br.action_probability_array)
combined_policy = main.combine_tabular_policies(game, nn_tab_policy, br)
print("value of table br policy", main.policy_value(game, combined_policy))

nn_br = neural_policies.nn_to_tabular_policy(game, hypernet, 1-nn_player, input_nets[ind])
print(nn_br.action_probability_array)
diff = np.abs(br.action_probability_array - nn_br.action_probability_array).sum()
print(diff)
combined_policy = main.combine_tabular_policies(game, nn_tab_policy, nn_br)
print("value of table br policy", main.policy_value(game, combined_policy))

ind 4
[[0.8914901  0.10850996]
 [0.06324194 0.9367581 ]
 [0.00770295 0.99229699]
 [0.00207829 0.99792176]
 [0.94578105 0.05421892]
 [0.31916466 0.68083537]
 [0.5        0.5       ]
 [0.5        0.5       ]
 [0.5        0.5       ]
 [0.5        0.5       ]
 [0.5        0.5       ]
 [0.5        0.5       ]]
[[0.5 0.5]
 [0.5 0.5]
 [0.5 0.5]
 [0.5 0.5]
 [0.5 0.5]
 [0.5 0.5]
 [0.  1. ]
 [0.  1. ]
 [0.  1. ]
 [0.  1. ]
 [1.  0. ]
 [1.  0. ]]
value of table br policy [-0.46546748  0.46546748]
[[0.5        0.5       ]
 [0.5        0.5       ]
 [0.5        0.5       ]
 [0.5        0.5       ]
 [0.5        0.5       ]
 [0.5        0.5       ]
 [0.96017069 0.03982927]
 [0.90566278 0.09433722]
 [0.03334772 0.96665221]
 [0.33968946 0.66031045]
 [0.82986069 0.1701393 ]
 [0.74316478 0.25683516]]
5.331690486520529
value of table br policy [-0.0595021  0.0595021]


In [17]:
for s in combined_policy.states:
    print(s.information_state_tensor(), s.information_state_string())

[1.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0] 0
[1.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0] 0pb
[1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0] 1
[1.0, 0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0] 1pb
[1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0] 2
[1.0, 0.0, 0.0, 0.0, 1.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0] 2pb
[0.0, 1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0] 1p
[0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0] 1b
[0.0, 1.0, 0.0, 0.0, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0] 2p
[0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0] 2b
[0.0, 1.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0] 0p
[0.0, 1.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0] 0b


In [ ]:
from nfn.common import state_dict_to_tensors
state_dict_to_tensors(input_nets[0].state_dict())[0][0].shape

In [ ]:
nn = input_nets[0]
w1 = list(nn.parameters())[0]

# relevant from here, next two cells

In [4]:
import policy_gradient
importlib.reload(policy_gradient)
importlib.reload(neural_policies)

hypernet_config = "../config/hypernet.yaml"
hypernet_config = yaml.safe_load(open(hypernet_config, "r"))
hypernet_train_config = "../config/hypernet_reinforce_train.yaml"
hypernet_train_config = yaml.safe_load(open(hypernet_train_config, "r"))

mlp = neural_policies.create_policy_net(game, nn_config)
hypernet_nn_output = neural_policies.create_hypernet_nn_output(game, mlp, hypernet_config)
trainer = policy_gradient.PolicyGradientHypernetTrainer(game, hypernet_nn_output, hypernet_train_config)

In [5]:
policy_nets = trainer.train_simultaneous_br(nn_config)
# trainer.train_best_response(policy_nets, 0)

  0%|          | 0/100000 [00:00<?, ?it/s]

[[0.33333333 0.33333333 0.33333333]
 [0.26185703 0.46273056 0.27541241]]
[[0.         0.         1.        ]
 [0.33333333 0.33333333 0.33333333]]
value of table br policy [ 0.20087352 -0.20087352]
[[0.42134953 0.12136761 0.4572829 ]
 [0.33333333 0.33333333 0.33333333]]
value of hypernet br policy [ 0.01128443 -0.01128443]
[[0.35675135 0.27289236 0.37035629]
 [0.33333333 0.33333333 0.33333333]]
[[0.33333333 0.33333333 0.33333333]
 [1.         0.         0.        ]]
value of table br policy [-0.09746394  0.09746394]
[[0.33333333 0.33333333 0.33333333]
 [0.37019143 0.12950855 0.50029999]]
value of hypernet br policy [ 0.0076363 -0.0076363]
[[0.33333333 0.33333333 0.33333333]
 [0.26185703 0.46273056 0.27541241]]
[[0.         0.         1.        ]
 [0.33333333 0.33333333 0.33333333]]
value of table br policy [ 0.20087352 -0.20087352]
[[0.40974024 0.12008872 0.47017103]
 [0.33333333 0.33333333 0.33333333]]
value of hypernet br policy [ 0.01606528 -0.01606528]
[[0.35675135 0.27289236 0.3703

  0%|          | 261/100000 [00:06<39:18, 42.29it/s]  

[[3.33333333e-01 3.33333333e-01 3.33333333e-01]
 [6.78038239e-01 4.40306234e-04 3.21521401e-01]]
[[0.         1.         0.        ]
 [0.33333333 0.33333333 0.33333333]]
value of table br policy [ 0.35651684 -0.35651684]
[[0.31381807 0.01667857 0.66950339]
 [0.33333333 0.33333333 0.33333333]]
value of hypernet br policy [-0.34694687  0.34694687]
[[0.31720075 0.01668318 0.66611606]
 [0.33333333 0.33333333 0.33333333]]
[[0.33333333 0.33333333 0.33333333]
 [1.         0.         0.        ]]
value of table br policy [-0.64943288  0.64943288]
[[3.33333333e-01 3.33333333e-01 3.33333333e-01]
 [6.80067182e-01 4.38642543e-04 3.19494128e-01]]
value of hypernet br policy [-0.34549134  0.34549134]
[[3.33333333e-01 3.33333333e-01 3.33333333e-01]
 [7.03098178e-01 4.29598149e-04 2.96472222e-01]]
[[0.         1.         0.        ]
 [0.33333333 0.33333333 0.33333333]]
value of table br policy [ 0.40662596 -0.40662596]
[[0.32554018 0.01904377 0.65541601]
 [0.33333333 0.33333333 0.33333333]]
value of h

  1%|          | 506/100000 [00:08<14:31, 114.19it/s]

[[3.33333333e-01 3.33333333e-01 3.33333333e-01]
 [9.55188513e-01 5.82974681e-05 4.47532125e-02]]
[[0.         1.         0.        ]
 [0.33333333 0.33333333 0.33333333]]
value of table br policy [ 0.9104353 -0.9104353]
[[0.01834636 0.95676517 0.02488848]
 [0.33333333 0.33333333 0.33333333]]
value of hypernet br policy [ 0.84812104 -0.84812104]
[[0.01814593 0.95728421 0.02456993]
 [0.33333333 0.33333333 0.33333333]]
[[0.33333333 0.33333333 0.33333333]
 [0.         0.         1.        ]]
value of table br policy [-0.93913828  0.93913828]
[[3.33333333e-01 3.33333333e-01 3.33333333e-01]
 [9.55506325e-01 5.75050217e-05 4.44361530e-02]]
value of hypernet br policy [ 0.84948307 -0.84948307]
[[3.33333333e-01 3.33333333e-01 3.33333333e-01]
 [9.54806685e-01 5.79433799e-05 4.51353602e-02]]
[[0.         1.         0.        ]
 [0.33333333 0.33333333 0.33333333]]
value of table br policy [ 0.90967133 -0.90967133]
[[0.0175471  0.95834297 0.02410987]
 [0.33333333 0.33333333 0.33333333]]
value of hyp

  1%|          | 753/100000 [00:10<15:16, 108.32it/s]

[[3.33333333e-01 3.33333333e-01 3.33333333e-01]
 [9.35015142e-01 8.18934204e-05 6.49029836e-02]]
[[0.         1.         0.        ]
 [0.33333333 0.33333333 0.33333333]]
value of table br policy [ 0.87011216 -0.87011216]
[[0.04578638 0.91258526 0.04162828]
 [0.33333333 0.33333333 0.33333333]]
value of hypernet br policy [ 0.75809979 -0.75809979]
[[0.04482014 0.91443443 0.0407454 ]
 [0.33333333 0.33333333 0.33333333]]
[[0.33333333 0.33333333 0.33333333]
 [0.         0.         1.        ]]
value of table br policy [-0.86961429  0.86961429]
[[3.33333333e-01 3.33333333e-01 3.33333333e-01]
 [9.35318291e-01 8.07165561e-05 6.46009967e-02]]
value of hypernet br policy [ 0.76099905 -0.76099905]
[[3.33333333e-01 3.33333333e-01 3.33333333e-01]
 [9.31897938e-01 8.26761316e-05 6.80194274e-02]]
[[0.         1.         0.        ]
 [0.33333333 0.33333333 0.33333333]]
value of table br policy [ 0.86387851 -0.86387851]
[[0.04437401 0.91390234 0.04172367]
 [0.33333333 0.33333333 0.33333333]]
value of h

  1%|          | 1004/100000 [00:12<14:20, 115.07it/s]

[[3.33333333e-01 3.33333333e-01 3.33333333e-01]
 [8.81756186e-01 9.84225480e-05 1.18145399e-01]]
[[0.         1.         0.        ]
 [0.33333333 0.33333333 0.33333333]]
value of table br policy [ 0.76361079 -0.76361079]
[[0.02986464 0.93366539 0.03646998]
 [0.33333333 0.33333333 0.33333333]]
value of hypernet br policy [ 0.68432836 -0.68432836]
[[0.02901862 0.9355123  0.03546909]
 [0.33333333 0.33333333 0.33333333]]
[[0.33333333 0.33333333 0.33333333]
 [0.         0.         1.        ]]
value of table br policy [-0.90649369  0.90649369]
[[3.33333333e-01 3.33333333e-01 3.33333333e-01]
 [8.82018745e-01 9.78938551e-05 1.17883325e-01]]
value of hypernet br policy [ 0.68699513 -0.68699513]
[[3.33333333e-01 3.33333333e-01 3.33333333e-01]
 [8.82470191e-01 9.74482027e-05 1.17432460e-01]]
[[0.         1.         0.        ]
 [0.33333333 0.33333333 0.33333333]]
value of table br policy [ 0.76503773 -0.76503773]
[[0.02802245 0.93754786 0.03442967]
 [0.33333333 0.33333333 0.33333333]]
value of h

  1%|▏         | 1257/100000 [00:14<13:30, 121.78it/s]

[[3.33333333e-01 3.33333333e-01 3.33333333e-01]
 [8.38856757e-01 1.27060761e-04 1.61016181e-01]]
[[0.         1.         0.        ]
 [0.33333333 0.33333333 0.33333333]]
value of table br policy [ 0.67784058 -0.67784058]
[[0.06044003 0.88216096 0.05739901]
 [0.33333333 0.33333333 0.33333333]]
value of hypernet br policy [ 0.55954638 -0.55954638]
[[0.07187523 0.86344504 0.06467968]
 [0.33333333 0.33333333 0.33333333]]
[[0.33333333 0.33333333 0.33333333]
 [0.         0.         1.        ]]
value of table br policy [-0.79156981  0.79156981]
[[3.33333333e-01 3.33333333e-01 3.33333333e-01]
 [8.42669845e-01 1.30348431e-04 1.57199800e-01]]
value of hypernet br policy [ 0.54865993 -0.54865993]
[[3.33333333e-01 3.33333333e-01 3.33333333e-01]
 [8.42193365e-01 1.30624685e-04 1.57675982e-01]]
[[0.         1.         0.        ]
 [0.33333333 0.33333333 0.33333333]]
value of table br policy [ 0.68451738 -0.68451738]
[[0.081029   0.84966916 0.06930179]
 [0.33333333 0.33333333 0.33333333]]
value of h

  2%|▏         | 1506/100000 [00:16<13:54, 118.07it/s]

[[3.33333333e-01 3.33333333e-01 3.33333333e-01]
 [8.32913160e-01 1.35864131e-04 1.66951045e-01]]
[[0.         1.         0.        ]
 [0.33333333 0.33333333 0.33333333]]
value of table br policy [ 0.66596211 -0.66596211]
[[0.08085887 0.866606   0.05253515]
 [0.33333333 0.33333333 0.33333333]]
value of hypernet br policy [ 0.54686517 -0.54686517]
[[0.07480173 0.87606132 0.04913691]
 [0.33333333 0.33333333 0.33333333]]
[[0.33333333 0.33333333 0.33333333]
 [0.         0.         1.        ]]
value of table br policy [-0.80125959  0.80125959]
[[3.33333333e-01 3.33333333e-01 3.33333333e-01]
 [8.31396699e-01 1.34157264e-04 1.68469101e-01]]
value of hypernet br policy [ 0.55251129 -0.55251129]
[[3.33333333e-01 3.33333333e-01 3.33333333e-01]
 [8.34553838e-01 1.33161273e-04 1.65313065e-01]]
[[0.         1.         0.        ]
 [0.33333333 0.33333333 0.33333333]]
value of table br policy [ 0.66924077 -0.66924077]
[[0.0695813  0.88408875 0.04632998]
 [0.33333333 0.33333333 0.33333333]]
value of h

  2%|▏         | 1755/100000 [00:18<14:19, 114.30it/s]

[[3.33333333e-01 3.33333333e-01 3.33333333e-01]
 [7.67415345e-01 1.37802781e-04 2.32446879e-01]]
[[0.         1.         0.        ]
 [0.33333333 0.33333333 0.33333333]]
value of table br policy [ 0.53496847 -0.53496847]
[[0.04486408 0.91874391 0.03639206]
 [0.33333333 0.33333333 0.33333333]]
value of hypernet br policy [ 0.47399854 -0.47399854]
[[0.04446607 0.91940886 0.03612507]
 [0.33333333 0.33333333 0.33333333]]
[[0.33333333 0.33333333 0.33333333]
 [0.         0.         1.        ]]
value of table br policy [-0.87494279  0.87494279]
[[3.33333333e-01 3.33333333e-01 3.33333333e-01]
 [7.66785204e-01 1.37659430e-04 2.33077094e-01]]
value of hypernet br policy [ 0.47335867 -0.47335867]
[[3.33333333e-01 3.33333333e-01 3.33333333e-01]
 [7.78849661e-01 1.35096736e-04 2.21015260e-01]]
[[0.         1.         0.        ]
 [0.33333333 0.33333333 0.33333333]]
value of table br policy [ 0.5578344 -0.5578344]
[[0.04182237 0.92502308 0.03315453]
 [0.33333333 0.33333333 0.33333333]]
value of hyp

  2%|▏         | 2003/100000 [00:21<15:48, 103.36it/s]

[[3.33333333e-01 3.33333333e-01 3.33333333e-01]
 [7.12294579e-01 1.49237210e-04 2.87556112e-01]]
[[0.         1.         0.        ]
 [0.33333333 0.33333333 0.33333333]]
value of table br policy [ 0.42473847 -0.42473847]
[[0.04766781 0.91523397 0.03709823]
 [0.33333333 0.33333333 0.33333333]]
value of hypernet br policy [ 0.3760158 -0.3760158]
[[0.04649705 0.91720545 0.03629753]
 [0.33333333 0.33333333 0.33333333]]
[[0.33333333 0.33333333 0.33333333]
 [0.         0.         1.        ]]
value of table br policy [-0.8707084  0.8707084]
[[3.33333333e-01 3.33333333e-01 3.33333333e-01]
 [7.11357534e-01 1.48698877e-04 2.88493812e-01]]
value of hypernet br policy [ 0.37544499 -0.37544499]
[[3.33333333e-01 3.33333333e-01 3.33333333e-01]
 [7.14117348e-01 1.48286519e-04 2.85734385e-01]]
[[0.         1.         0.        ]
 [0.33333333 0.33333333 0.33333333]]
value of table br policy [ 0.42838296 -0.42838296]
[[0.04532332 0.91924983 0.03542675]
 [0.33333333 0.33333333 0.33333333]]
value of hyper

  2%|▏         | 2263/100000 [00:23<14:34, 111.80it/s]

[[3.33333333e-01 3.33333333e-01 3.33333333e-01]
 [7.15600371e-01 1.67042323e-04 2.84232616e-01]]
[[0.         1.         0.        ]
 [0.33333333 0.33333333 0.33333333]]
value of table br policy [ 0.43136775 -0.43136775]
[[0.09173117 0.86537504 0.04289379]
 [0.33333333 0.33333333 0.33333333]]
value of hypernet br policy [ 0.36866491 -0.36866491]
[[0.09469132 0.86185288 0.04345575]
 [0.33333333 0.33333333 0.33333333]]
[[0.33333333 0.33333333 0.33333333]
 [0.         0.         1.        ]]
value of table br policy [-0.76716156  0.76716156]
[[3.33333333e-01 3.33333333e-01 3.33333333e-01]
 [7.18804181e-01 1.67627702e-04 2.81028211e-01]]
value of hypernet br policy [ 0.37266465 -0.37266465]
[[3.33333333e-01 3.33333333e-01 3.33333333e-01]
 [7.25893557e-01 1.66152968e-04 2.73940325e-01]]
[[0.         1.         0.        ]
 [0.33333333 0.33333333 0.33333333]]
value of table br policy [ 0.45195323 -0.45195323]
[[0.09324946 0.86514479 0.04160579]
 [0.33333333 0.33333333 0.33333333]]
value of h

  3%|▎         | 2505/100000 [00:25<14:12, 114.43it/s]

[[3.33333333e-01 3.33333333e-01 3.33333333e-01]
 [6.48222566e-01 1.69194202e-04 3.51608247e-01]]
[[1.         0.         0.        ]
 [0.33333333 0.33333333 0.33333333]]
value of table br policy [ 0.35143905 -0.35143905]
[[0.07419953 0.8894093  0.0363911 ]
 [0.33333333 0.33333333 0.33333333]]
value of hypernet br policy [ 0.26630477 -0.26630477]
[[0.07316016 0.89081168 0.03602808]
 [0.33333333 0.33333333 0.33333333]]
[[0.33333333 0.33333333 0.33333333]
 [0.         0.         1.        ]]
value of table br policy [-0.81765153  0.81765153]
[[3.33333333e-01 3.33333333e-01 3.33333333e-01]
 [6.47178829e-01 1.68826431e-04 3.52652282e-01]]
value of hypernet br policy [ 0.26484491 -0.26484491]
[[3.33333333e-01 3.33333333e-01 3.33333333e-01]
 [6.48254335e-01 1.68689323e-04 3.51576954e-01]]
[[1.         0.         0.        ]
 [0.33333333 0.33333333 0.33333333]]
value of table br policy [ 0.35140826 -0.35140826]
[[0.07228052 0.89200497 0.03571446]
 [0.33333333 0.33333333 0.33333333]]
value of h

  3%|▎         | 2764/100000 [00:27<15:34, 104.03it/s]

[[3.33333333e-01 3.33333333e-01 3.33333333e-01]
 [6.47291005e-01 1.76674090e-04 3.52532327e-01]]
[[1.         0.         0.        ]
 [0.33333333 0.33333333 0.33333333]]
value of table br policy [ 0.35235565 -0.35235565]
[[0.09642535 0.8690604  0.03451427]
 [0.33333333 0.33333333 0.33333333]]
value of hypernet br policy [ 0.26780444 -0.26780444]
[[0.09888207 0.8665235  0.03459439]
 [0.33333333 0.33333333 0.33333333]]
[[0.33333333 0.33333333 0.33333333]
 [0.         0.         1.        ]]
value of table br policy [-0.76764143  0.76764143]
[[3.33333333e-01 3.33333333e-01 3.33333333e-01]
 [6.50076985e-01 1.77166512e-04 3.49745870e-01]]
value of hypernet br policy [ 0.27232716 -0.27232716]
[[3.33333333e-01 3.33333333e-01 3.33333333e-01]
 [6.50077105e-01 1.77166541e-04 3.49745780e-01]]
[[1.         0.         0.        ]
 [0.33333333 0.33333333 0.33333333]]
value of table br policy [ 0.34956861 -0.34956861]
[[0.09974989 0.86571562 0.03453445]
 [0.33333333 0.33333333 0.33333333]]
value of h

  3%|▎         | 3019/100000 [00:29<13:42, 117.87it/s]

[[3.33333333e-01 3.33333333e-01 3.33333333e-01]
 [6.47118151e-01 1.91279978e-04 3.52690548e-01]]
[[1.         0.         0.        ]
 [0.33333333 0.33333333 0.33333333]]
value of table br policy [ 0.35249927 -0.35249927]
[[0.14333434 0.82079142 0.03587429]
 [0.33333333 0.33333333 0.33333333]]
value of hypernet br policy [ 0.26898086 -0.26898086]
[[0.13953085 0.82514095 0.03532817]
 [0.33333333 0.33333333 0.33333333]]
[[0.33333333 0.33333333 0.33333333]
 [0.         0.         1.        ]]
value of table br policy [-0.6856101  0.6856101]
[[3.33333333e-01 3.33333333e-01 3.33333333e-01]
 [6.43943727e-01 1.90435909e-04 3.55865806e-01]]
value of hypernet br policy [ 0.26458995 -0.26458995]
[[3.33333333e-01 3.33333333e-01 3.33333333e-01]
 [6.49042010e-01 1.89817642e-04 3.50768149e-01]]
[[1.         0.         0.        ]
 [0.33333333 0.33333333 0.33333333]]
value of table br policy [ 0.35057833 -0.35057833]
[[0.13537964 0.83020884 0.03441149]
 [0.33333333 0.33333333 0.33333333]]
value of hyp

  3%|▎         | 3254/100000 [00:31<14:19, 112.54it/s]

[[3.33333333e-01 3.33333333e-01 3.33333333e-01]
 [6.42913222e-01 1.96056964e-04 3.56890738e-01]]
[[1.         0.         0.        ]
 [0.33333333 0.33333333 0.33333333]]
value of table br policy [ 0.35669468 -0.35669468]
[[0.15658489 0.81011707 0.03329803]
 [0.33333333 0.33333333 0.33333333]]
value of hypernet br policy [ 0.26616348 -0.26616348]
[[0.15619959 0.81100339 0.032797  ]
 [0.33333333 0.33333333 0.33333333]]
[[0.33333333 0.33333333 0.33333333]
 [0.         0.         1.        ]]
value of table br policy [-0.6548038  0.6548038]
[[3.33333333e-01 3.33333333e-01 3.33333333e-01]
 [6.43562198e-01 1.95862958e-04 3.56241912e-01]]
value of hypernet br policy [ 0.26753149 -0.26753149]
[[3.33333333e-01 3.33333333e-01 3.33333333e-01]
 [6.46774650e-01 1.96929075e-04 3.53028387e-01]]
[[1.         0.         0.        ]
 [0.33333333 0.33333333 0.33333333]]
value of table br policy [ 0.35283146 -0.35283146]
[[0.15832809 0.80893302 0.03273885]
 [0.33333333 0.33333333 0.33333333]]
value of hyp

  4%|▎         | 3504/100000 [00:34<13:48, 116.50it/s]

[[3.33333333e-01 3.33333333e-01 3.33333333e-01]
 [6.11513019e-01 1.91408151e-04 3.88295621e-01]]
[[1.         0.         0.        ]
 [0.33333333 0.33333333 0.33333333]]
value of table br policy [ 0.38810421 -0.38810421]
[[0.13247964 0.83901602 0.02850441]
 [0.33333333 0.33333333 0.33333333]]
value of hypernet br policy [ 0.22127352 -0.22127352]
[[0.14255099 0.82820094 0.02924804]
 [0.33333333 0.33333333 0.33333333]]
[[0.33333333 0.33333333 0.33333333]
 [0.         0.         1.        ]]
value of table br policy [-0.68564995  0.68564995]
[[3.33333333e-01 3.33333333e-01 3.33333333e-01]
 [6.20919943e-01 1.93707150e-04 3.78886342e-01]]
value of hypernet br policy [ 0.23628044 -0.23628044]
[[3.33333333e-01 3.33333333e-01 3.33333333e-01]
 [6.31339610e-01 1.92619395e-04 3.68467808e-01]]
[[1.         0.         0.        ]
 [0.33333333 0.33333333 0.33333333]]
value of table br policy [ 0.36827519 -0.36827519]
[[0.14272811 0.82956964 0.02770235]
 [0.33333333 0.33333333 0.33333333]]
value of h

  4%|▍         | 3763/100000 [00:36<14:36, 109.75it/s]

[[0.33333333 0.33333333 0.33333333]
 [0.68397504 0.00192839 0.31409651]]
[[0.         1.         0.        ]
 [0.33333333 0.33333333 0.33333333]]
value of table br policy [ 0.36987853 -0.36987853]
[[0.4933058  0.43383503 0.07285914]
 [0.33333333 0.33333333 0.33333333]]
value of hypernet br policy [ 0.26476728 -0.26476728]
[[0.47859243 0.44898316 0.07242446]
 [0.33333333 0.33333333 0.33333333]]
[[0.33333333 0.33333333 0.33333333]
 [0.         1.         0.        ]]
value of table br policy [-0.40616796  0.40616796]
[[0.33333333 0.33333333 0.33333333]
 [0.68127799 0.00203183 0.31669018]]
value of hypernet br policy [ 0.26509285 -0.26509285]
[[0.33333333 0.33333333 0.33333333]
 [0.71147132 0.00197261 0.28655612]]
[[0.         1.         0.        ]
 [0.33333333 0.33333333 0.33333333]]
value of table br policy [ 0.42491519 -0.42491519]
[[0.45707121 0.47676346 0.06616531]
 [0.33333333 0.33333333 0.33333333]]
value of hypernet br policy [ 0.28571477 -0.28571477]
[[0.45707121 0.47676346 0.06

  4%|▍         | 4007/100000 [00:38<12:58, 123.30it/s]

[[0.33333333 0.33333333 0.33333333]
 [0.68789381 0.00296608 0.30914009]]
[[0.         1.         0.        ]
 [0.33333333 0.33333333 0.33333333]]
value of table br policy [ 0.37875372 -0.37875372]
[[0.49324605 0.43464711 0.07210678]
 [0.33333333 0.33333333 0.33333333]]
value of hypernet br policy [ 0.2662554 -0.2662554]
[[0.48416016 0.4443703  0.07146952]
 [0.33333333 0.33333333 0.33333333]]
[[0.33333333 0.33333333 0.33333333]
 [0.         1.         0.        ]]
value of table br policy [-0.41269063  0.41269063]
[[0.33333333 0.33333333 0.33333333]
 [0.68344873 0.00285277 0.31369847]]
value of hypernet br policy [ 0.26616327 -0.26616327]
[[0.33333333 0.33333333 0.33333333]
 [0.68788135 0.00286104 0.3092576 ]]
[[0.         1.         0.        ]
 [0.33333333 0.33333333 0.33333333]]
value of table br policy [ 0.37862375 -0.37862375]
[[0.47253427 0.45730338 0.07016231]
 [0.33333333 0.33333333 0.33333333]]
value of hypernet br policy [ 0.26986618 -0.26986618]
[[0.47253427 0.45730338 0.0701

  4%|▍         | 4254/100000 [00:40<13:55, 114.61it/s]

[[0.33333333 0.33333333 0.33333333]
 [0.7048921  0.0072132  0.28789467]]
[[0.         1.         0.        ]
 [0.33333333 0.33333333 0.33333333]]
value of table br policy [ 0.41699743 -0.41699743]
[[0.61564779 0.29807749 0.08627471]
 [0.33333333 0.33333333 0.33333333]]
value of hypernet br policy [ 0.23690643 -0.23690643]
[[0.61430025 0.29992658 0.08577323]
 [0.33333333 0.33333333 0.33333333]]
[[0.33333333 0.33333333 0.33333333]
 [0.         1.         0.        ]]
value of table br policy [-0.52852702  0.52852702]
[[0.33333333 0.33333333 0.33333333]
 [0.70486104 0.00737998 0.28775889]]
value of hypernet br policy [ 0.23751165 -0.23751165]
[[0.33333333 0.33333333 0.33333333]
 [0.69166023 0.00748086 0.30085897]]
[[0.         1.         0.        ]
 [0.33333333 0.33333333 0.33333333]]
value of table br policy [ 0.39080125 -0.39080125]
[[0.62474805 0.28517315 0.09007872]
 [0.33333333 0.33333333 0.33333333]]
value of hypernet br policy [ 0.23310343 -0.23310343]
[[0.62474805 0.28517315 0.09

  5%|▍         | 4504/100000 [00:42<14:11, 112.09it/s]

[[0.33333333 0.33333333 0.33333333]
 [0.73960686 0.02787022 0.23252285]]
[[0.         1.         0.        ]
 [0.33333333 0.33333333 0.33333333]]
value of table br policy [ 0.50708401 -0.50708401]
[[0.751791   0.14998294 0.09822611]
 [0.33333333 0.33333333 0.33333333]]
value of hypernet br policy [ 0.15999884 -0.15999884]
[[0.75051439 0.15105398 0.0984317 ]
 [0.33333333 0.33333333 0.33333333]]
[[0.33333333 0.33333333 0.33333333]
 [0.         1.         0.        ]]
value of table br policy [-0.65208269  0.65208269]
[[0.33333333 0.33333333 0.33333333]
 [0.73914903 0.02783361 0.23301736]]
value of hypernet br policy [ 0.16043057 -0.16043057]
[[0.33333333 0.33333333 0.33333333]
 [0.73581725 0.0279629  0.23621991]]
[[0.         1.         0.        ]
 [0.33333333 0.33333333 0.33333333]]
value of table br policy [ 0.49959734 -0.49959734]
[[0.75131243 0.1491539  0.09953365]
 [0.33333333 0.33333333 0.33333333]]
value of hypernet br policy [ 0.16052765 -0.16052765]
[[0.75131243 0.1491539  0.09

  5%|▍         | 4756/100000 [00:44<13:53, 114.34it/s]

[[0.33333333 0.33333333 0.33333333]
 [0.71799439 0.01869193 0.26331365]]
[[0.         1.         0.        ]
 [0.33333333 0.33333333 0.33333333]]
value of table br policy [ 0.45468074 -0.45468074]
[[0.67499709 0.2307763  0.09422661]
 [0.33333333 0.33333333 0.33333333]]
value of hypernet br policy [ 0.20415558 -0.20415558]
[[0.67788583 0.2283085  0.09380572]
 [0.33333333 0.33333333 0.33333333]]
[[0.33333333 0.33333333 0.33333333]
 [0.         1.         0.        ]]
value of table br policy [-0.58408011  0.58408011]
[[0.33333333 0.33333333 0.33333333]
 [0.71909779 0.01890009 0.26200217]]
value of hypernet br policy [ 0.20347172 -0.20347172]
[[0.33333333 0.33333333 0.33333333]
 [0.70713693 0.01926732 0.27359572]]
[[0.         1.         0.        ]
 [0.33333333 0.33333333 0.33333333]]
value of table br policy [ 0.43354121 -0.43354121]
[[0.68628168 0.21639356 0.09732474]
 [0.33333333 0.33333333 0.33333333]]
value of hypernet br policy [ 0.20140972 -0.20140972]
[[0.68628168 0.21639356 0.09

  5%|▌         | 5006/100000 [00:47<13:36, 116.40it/s]

[[0.33333333 0.33333333 0.33333333]
 [0.73067898 0.03460055 0.23472051]]
[[0.         1.         0.        ]
 [0.33333333 0.33333333 0.33333333]]
value of table br policy [ 0.49595846 -0.49595846]
[[0.73199463 0.17384788 0.09415749]
 [0.33333333 0.33333333 0.33333333]]
value of hypernet br policy [ 0.16716707 -0.16716707]
[[0.72474325 0.18040058 0.0948562 ]
 [0.33333333 0.33333333 0.33333333]]
[[0.33333333 0.33333333 0.33333333]
 [0.         1.         0.        ]]
value of table br policy [-0.62988705  0.62988705]
[[0.33333333 0.33333333 0.33333333]
 [0.72772574 0.03397785 0.23829642]]
value of hypernet br policy [ 0.17056555 -0.17056555]
[[0.33333333 0.33333333 0.33333333]
 [0.71179032 0.03464745 0.25356215]]
[[0.         1.         0.        ]
 [0.33333333 0.33333333 0.33333333]]
value of table br policy [ 0.45822817 -0.45822817]
[[0.72823238 0.17165375 0.10011383]
 [0.33333333 0.33333333 0.33333333]]
value of hypernet br policy [ 0.17028599 -0.17028599]
[[0.72823238 0.17165375 0.10

  5%|▌         | 5254/100000 [00:49<13:31, 116.69it/s]

[[0.33333333 0.33333333 0.33333333]
 [0.72235626 0.0540056  0.22363809]]
[[0.         1.         0.        ]
 [0.33333333 0.33333333 0.33333333]]
value of table br policy [ 0.49871817 -0.49871817]
[[0.77968961 0.12479047 0.09551993]
 [0.33333333 0.33333333 0.33333333]]
value of hypernet br policy [ 0.13065516 -0.13065516]
[[0.77552783 0.1282721  0.09620001]
 [0.33333333 0.33333333 0.33333333]]
[[0.33333333 0.33333333 0.33333333]
 [0.         1.         0.        ]]
value of table br policy [-0.67932782  0.67932782]
[[0.33333333 0.33333333 0.33333333]
 [0.7205534  0.05467925 0.22476733]]
value of hypernet br policy [ 0.13144646 -0.13144646]
[[0.33333333 0.33333333 0.33333333]
 [0.71063745 0.0553957  0.23396686]]
[[0.         1.         0.        ]
 [0.33333333 0.33333333 0.33333333]]
value of table br policy [ 0.47667059 -0.47667059]
[[0.77803522 0.122187   0.09977776]
 [0.33333333 0.33333333 0.33333333]]
value of hypernet br policy [ 0.13179904 -0.13179904]
[[0.77803522 0.122187   0.09

  5%|▌         | 5498/100000 [00:51<13:11, 119.34it/s]

[[0.33333333 0.33333333 0.33333333]
 [0.70739317 0.10981996 0.18278682]]
[[0.         1.         0.        ]
 [0.33333333 0.33333333 0.33333333]]
value of table br policy [ 0.52460635 -0.52460635]
[[0.83047211 0.07361207 0.09591588]
 [0.33333333 0.33333333 0.33333333]]
value of hypernet br policy [ 0.04189754 -0.04189754]
[[0.82579261 0.07651148 0.09769588]
 [0.33333333 0.33333333 0.33333333]]
[[0.33333333 0.33333333 0.33333333]
 [0.         1.         0.        ]]
value of table br policy [-0.72809673  0.72809673]
[[0.33333333 0.33333333 0.33333333]
 [0.70717853 0.10629819 0.1865233 ]]
value of hypernet br policy [ 0.04738187 -0.04738187]


  6%|▌         | 5522/100000 [00:51<19:10, 82.12it/s] 

[[0.33333333 0.33333333 0.33333333]
 [0.70745093 0.10632221 0.18622681]]
[[0.         1.         0.        ]
 [0.33333333 0.33333333 0.33333333]]
value of table br policy [ 0.52122411 -0.52122411]
[[0.82347023 0.078502   0.09802775]
 [0.33333333 0.33333333 0.33333333]]
value of hypernet br policy [ 0.04778891 -0.04778891]
[[0.82347023 0.078502   0.09802775]
 [0.33333333 0.33333333 0.33333333]]
[[0.33333333 0.33333333 0.33333333]
 [0.         1.         0.        ]]
value of table br policy [-0.72544248  0.72544248]
[[0.33333333 0.33333333 0.33333333]
 [0.70899409 0.10287001 0.18813586]]
value of hypernet br policy [ 0.05168532 -0.05168532]


  6%|▌         | 5766/100000 [00:53<13:31, 116.08it/s]

[[0.33333333 0.33333333 0.33333333]
 [0.70674473 0.06759735 0.22565798]]
[[0.         1.         0.        ]
 [0.33333333 0.33333333 0.33333333]]
value of table br policy [ 0.48108675 -0.48108675]
[[0.77769905 0.12398216 0.09831873]
 [0.33333333 0.33333333 0.33333333]]
value of hypernet br policy [ 0.11972962 -0.11972962]
[[0.78221452 0.12141174 0.09637368]
 [0.33333333 0.33333333 0.33333333]]
[[0.33333333 0.33333333 0.33333333]
 [0.         1.         0.        ]]
value of table br policy [-0.68584085  0.68584085]
[[0.33333333 0.33333333 0.33333333]
 [0.70720816 0.06940141 0.22339043]]
value of hypernet br policy [ 0.11772582 -0.11772582]
[[0.33333333 0.33333333 0.33333333]
 [0.71904886 0.06825236 0.21269873]]
[[0.         1.         0.        ]
 [0.33333333 0.33333333 0.33333333]]
value of table br policy [ 0.50635013 -0.50635013]
[[0.78000492 0.12660639 0.09338871]
 [0.33333333 0.33333333 0.33333333]]
value of hypernet br policy [ 0.11599899 -0.11599899]
[[0.78000492 0.12660639 0.09

  6%|▌         | 6005/100000 [00:56<14:49, 105.64it/s]

[[0.33333333 0.33333333 0.33333333]
 [0.70012188 0.08012801 0.21975011]]
[[0.         1.         0.        ]
 [0.33333333 0.33333333 0.33333333]]
value of table br policy [ 0.48037177 -0.48037177]
[[0.78393441 0.11739593 0.09866961]
 [0.33333333 0.33333333 0.33333333]]
value of hypernet br policy [ 0.10467371 -0.10467371]
[[0.7833721  0.11783386 0.098794  ]
 [0.33333333 0.33333333 0.33333333]]
[[0.33333333 0.33333333 0.33333333]
 [0.         1.         0.        ]]
value of table br policy [-0.68457811  0.68457811]
[[0.33333333 0.33333333 0.33333333]
 [0.69981921 0.08043867 0.21974215]]
value of hypernet br policy [ 0.10450471 -0.10450471]
[[0.33333333 0.33333333 0.33333333]
 [0.70062637 0.08032157 0.21905211]]
[[0.         1.         0.        ]
 [0.33333333 0.33333333 0.33333333]]
value of table br policy [ 0.48157427 -0.48157427]
[[0.78324366 0.118036   0.09872028]
 [0.33333333 0.33333333 0.33333333]]
value of hypernet br policy [ 0.10426625 -0.10426625]
[[0.78324366 0.118036   0.09

  6%|▋         | 6264/100000 [00:58<13:27, 116.13it/s]

[[0.33333333 0.33333333 0.33333333]
 [0.68653983 0.11788695 0.19557321]]
[[0.         1.         0.        ]
 [0.33333333 0.33333333 0.33333333]]
value of table br policy [ 0.49096662 -0.49096662]
[[0.80317652 0.09450499 0.10231849]
 [0.33333333 0.33333333 0.33333333]]
value of hypernet br policy [ 0.05061087 -0.05061087]
[[0.80455428 0.09391036 0.10153538]
 [0.33333333 0.33333333 0.33333333]]
[[0.33333333 0.33333333 0.33333333]
 [0.         1.         0.        ]]
value of table br policy [-0.7030189  0.7030189]
[[0.33333333 0.33333333 0.33333333]
 [0.68679035 0.11711827 0.19609135]]
value of hypernet br policy [ 0.05177798 -0.05177798]
[[0.33333333 0.33333333 0.33333333]
 [0.6856851  0.11738361 0.1969313 ]]
[[0.         1.         0.        ]
 [0.33333333 0.33333333 0.33333333]]
value of table br policy [ 0.4887538 -0.4887538]
[[0.80403709 0.09408607 0.10187689]
 [0.33333333 0.33333333 0.33333333]]
value of hypernet br policy [ 0.05204743 -0.05204743]
[[0.80403709 0.09408607 0.101876

  7%|▋         | 6506/100000 [01:00<13:31, 115.16it/s]

[[0.33333333 0.33333333 0.33333333]
 [0.66110235 0.17219406 0.16670364]]
[[0.         1.         0.        ]
 [0.33333333 0.33333333 0.33333333]]
value of table br policy [ 0.49439871 -0.49439871]
[[0.83487028 0.06657675 0.09855299]
 [0.33333333 0.33333333 0.33333333]]
value of hypernet br policy [-0.0198517  0.0198517]
[[0.82999891 0.0696228  0.10037822]
 [0.33333333 0.33333333 0.33333333]]
[[0.33333333 0.33333333 0.33333333]
 [0.         1.         0.        ]]
value of table br policy [-0.7296207  0.7296207]
[[0.33333333 0.33333333 0.33333333]
 [0.66190958 0.16719773 0.1708927 ]]
value of hypernet br policy [-0.0124055  0.0124055]
[[0.33333333 0.33333333 0.33333333]
 [0.6495384  0.17024475 0.18021682]]
[[0.         1.         0.        ]
 [0.33333333 0.33333333 0.33333333]]
value of table br policy [ 0.46932158 -0.46932158]
[[0.8286199  0.06694443 0.10443563]
 [0.33333333 0.33333333 0.33333333]]
value of hypernet br policy [-0.01037382  0.01037382]
[[0.8286199  0.06694443 0.10443563

  7%|▋         | 6755/100000 [01:02<13:40, 113.58it/s]

[[0.33333333 0.33333333 0.33333333]
 [0.66657633 0.15580299 0.17762065]]
[[0.         1.         0.        ]
 [0.33333333 0.33333333 0.33333333]]
value of table br policy [ 0.48895568 -0.48895568]
[[0.81990743 0.07885469 0.10123793]
 [0.33333333 0.33333333 0.33333333]]
value of hypernet br policy [ 0.00473527 -0.00473527]
[[0.81494051 0.08176336 0.10329609]
 [0.33333333 0.33333333 0.33333333]]
[[0.33333333 0.33333333 0.33333333]
 [0.         1.         0.        ]]
value of table br policy [-0.71164442  0.71164442]
[[0.33333333 0.33333333 0.33333333]
 [0.66713893 0.1519509  0.18091023]]
value of hypernet br policy [ 0.01013891 -0.01013891]
[[0.33333333 0.33333333 0.33333333]
 [0.66961449 0.15158637 0.17879918]]
[[0.         1.         0.        ]
 [0.33333333 0.33333333 0.33333333]]
value of table br policy [ 0.49081531 -0.49081531]
[[0.81289852 0.08430064 0.10280089]
 [0.33333333 0.33333333 0.33333333]]
value of hypernet br policy [ 0.01024355 -0.01024355]
[[0.81289852 0.08430064 0.10

  7%|▋         | 7018/100000 [01:04<12:36, 122.85it/s]

[[0.33333333 0.33333333 0.33333333]
 [0.67434978 0.12774965 0.19790055]]
[[0.         1.         0.        ]
 [0.33333333 0.33333333 0.33333333]]
value of table br policy [ 0.47644924 -0.47644924]
[[0.80393094 0.09694327 0.09912577]
 [0.33333333 0.33333333 0.33333333]]
value of hypernet br policy [ 0.04840286 -0.04840286]
[[0.7983346  0.10025852 0.10140681]
 [0.33333333 0.33333333 0.33333333]]
[[0.33333333 0.33333333 0.33333333]
 [0.         1.         0.        ]]
value of table br policy [-0.69692779  0.69692779]
[[0.33333333 0.33333333 0.33333333]
 [0.67478377 0.12363656 0.20157969]]
value of hypernet br policy [ 0.05377736 -0.05377736]
[[0.33333333 0.33333333 0.33333333]
 [0.68234313 0.12240995 0.19524691]]
[[0.         1.         0.        ]
 [0.33333333 0.33333333 0.33333333]]
value of table br policy [ 0.48709622 -0.48709622]
[[0.79480535 0.10607354 0.09912112]
 [0.33333333 0.33333333 0.33333333]]
value of hypernet br policy [ 0.05405802 -0.05405802]
[[0.79480535 0.10607354 0.09

  7%|▋         | 7270/100000 [01:06<13:01, 118.70it/s]

[[0.33333333 0.33333333 0.33333333]
 [0.64394462 0.17926052 0.17679492]]
[[0.         1.         0.        ]
 [0.33333333 0.33333333 0.33333333]]
value of table br policy [ 0.4671497 -0.4671497]
[[0.82347405 0.07451759 0.1020084 ]
 [0.33333333 0.33333333 0.33333333]]
value of hypernet br policy [-0.01462118  0.01462118]
[[0.81957346 0.07699514 0.10343142]
 [0.33333333 0.33333333 0.33333333]]
[[0.33333333 0.33333333 0.33333333]
 [0.         1.         0.        ]]
value of table br policy [-0.71614204  0.71614204]
[[0.33333333 0.33333333 0.33333333]
 [0.64353782 0.1772671  0.17919515]]
value of hypernet br policy [-0.01089474  0.01089474]
[[0.33333333 0.33333333 0.33333333]
 [0.64999712 0.17609343 0.1739094 ]]
[[0.         1.         0.        ]
 [0.33333333 0.33333333 0.33333333]]
value of table br policy [ 0.47608772 -0.47608772]
[[0.81758803 0.08032236 0.10208949]
 [0.33333333 0.33333333 0.33333333]]
value of hypernet br policy [-0.01192574  0.01192574]
[[0.81758803 0.08032236 0.1020

  8%|▊         | 7504/100000 [01:08<13:17, 115.98it/s]

[[0.33333333 0.33333333 0.33333333]
 [0.63329977 0.19504374 0.17165653]]
[[0.         1.         0.        ]
 [0.33333333 0.33333333 0.33333333]]
value of table br policy [ 0.46164323 -0.46164323]
[[0.8199138  0.076576   0.10351017]
 [0.33333333 0.33333333 0.33333333]]
value of hypernet br policy [-0.02918866  0.02918866]
[[0.82338679 0.07492135 0.10169183]
 [0.33333333 0.33333333 0.33333333]]
[[0.33333333 0.33333333 0.33333333]
 [0.         1.         0.        ]]
value of table br policy [-0.72169495  0.72169495]
[[0.33333333 0.33333333 0.33333333]
 [0.63293207 0.19662312 0.17044479]]
value of hypernet br policy [-0.03127378  0.03127378]
[[0.33333333 0.33333333 0.33333333]
 [0.63215047 0.19870588 0.16914365]]
[[0.         1.         0.        ]
 [0.33333333 0.33333333 0.33333333]]
value of table br policy [ 0.46300682 -0.46300682]
[[0.82380682 0.07437178 0.10182148]
 [0.33333333 0.33333333 0.33333333]]
value of hypernet br policy [-0.0340529  0.0340529]
[[0.82380682 0.07437178 0.1018

  8%|▊         | 7757/100000 [01:11<12:30, 122.83it/s]

[[0.33333333 0.33333333 0.33333333]
 [0.61762851 0.22226189 0.16010962]]
[[0.         1.         0.        ]
 [0.33333333 0.33333333 0.33333333]]
value of table br policy [ 0.45751889 -0.45751889]
[[0.82419598 0.07205193 0.10375213]
 [0.33333333 0.33333333 0.33333333]]
value of hypernet br policy [-0.05928066  0.05928066]
[[0.82400018 0.07209113 0.10390861]
 [0.33333333 0.33333333 0.33333333]]
[[0.33333333 0.33333333 0.33333333]
 [0.         1.         0.        ]]
value of table br policy [-0.72009157  0.72009157]
[[0.33333333 0.33333333 0.33333333]
 [0.61716121 0.22307098 0.15976775]]
value of hypernet br policy [-0.06013723  0.06013723]
[[0.33333333 0.33333333 0.33333333]
 [0.61790955 0.22281855 0.15927187]]
[[0.         1.         0.        ]
 [0.33333333 0.33333333 0.33333333]]
value of table br policy [ 0.45863768 -0.45863768]
[[0.82414132 0.07213219 0.10372648]
 [0.33333333 0.33333333 0.33333333]]
value of hypernet br policy [-0.06027031  0.06027031]
[[0.82414132 0.07213219 0.10

  8%|▊         | 8018/100000 [01:13<13:01, 117.69it/s]

[[0.33333333 0.33333333 0.33333333]
 [0.61084241 0.22243516 0.16672251]]
[[0.         1.         0.        ]
 [0.33333333 0.33333333 0.33333333]]
value of table br policy [ 0.4441199 -0.4441199]
[[0.8191883  0.06987102 0.11094057]
 [0.33333333 0.33333333 0.33333333]]
value of hypernet br policy [-0.05769816  0.05769816]
[[0.81722504 0.07116038 0.11161467]
 [0.33333333 0.33333333 0.33333333]]
[[0.33333333 0.33333333 0.33333333]
 [0.         1.         0.        ]]
value of table br policy [-0.70561037  0.70561037]
[[0.33333333 0.33333333 0.33333333]
 [0.61182702 0.21923718 0.16893584]]
value of hypernet br policy [-0.05341  0.05341]
[[0.33333333 0.33333333 0.33333333]
 [0.60983843 0.21974888 0.17041269]]
[[0.         1.         0.        ]
 [0.33333333 0.33333333 0.33333333]]
value of table br policy [ 0.43942574 -0.43942574]
[[0.81620103 0.07132207 0.11247697]
 [0.33333333 0.33333333 0.33333333]]
value of hypernet br policy [-0.05280359  0.05280359]
[[0.81620103 0.07132207 0.11247697]


  8%|▊         | 8254/100000 [01:15<13:33, 112.77it/s]

[[0.33333333 0.33333333 0.33333333]
 [0.56904709 0.28824025 0.14271259]]
[[0.         1.         0.        ]
 [0.33333333 0.33333333 0.33333333]]
value of table br policy [ 0.4263345 -0.4263345]
[[0.82953155 0.05915273 0.11131573]
 [0.33333333 0.33333333 0.33333333]]
value of hypernet br policy [-0.12675916  0.12675916]
[[0.82817304 0.05898448 0.1128424 ]
 [0.33333333 0.33333333 0.33333333]]
[[0.33333333 0.33333333 0.33333333]
 [0.         1.         0.        ]]
value of table br policy [-0.71533064  0.71533064]
[[0.33333333 0.33333333 0.33333333]
 [0.57212073 0.28459844 0.14328086]]
value of hypernet br policy [-0.12418522  0.12418522]
[[0.33333333 0.33333333 0.33333333]
 [0.57702118 0.28321797 0.13976085]]
[[0.         1.         0.        ]
 [0.33333333 0.33333333 0.33333333]]
value of table br policy [ 0.43726033 -0.43726033]
[[0.82878149 0.06097268 0.11024588]
 [0.33333333 0.33333333 0.33333333]]
value of hypernet br policy [-0.12462426  0.12462426]
[[0.82878149 0.06097268 0.1102

  9%|▊         | 8513/100000 [01:17<13:28, 113.16it/s]

[[0.33333333 0.33333333 0.33333333]
 [0.61546302 0.21793142 0.16660555]]
[[0.         1.         0.        ]
 [0.33333333 0.33333333 0.33333333]]
value of table br policy [ 0.44885747 -0.44885747]
[[0.81165045 0.08447982 0.10386968]
 [0.33333333 0.33333333 0.33333333]]
value of hypernet br policy [-0.04503075  0.04503075]
[[0.81707877 0.08173336 0.10118792]
 [0.33333333 0.33333333 0.33333333]]
[[0.33333333 0.33333333 0.33333333]
 [0.         1.         0.        ]]
value of table br policy [-0.71589085  0.71589085]
[[0.33333333 0.33333333 0.33333333]
 [0.6122216  0.22497918 0.16279918]]
value of hypernet br policy [-0.05325741  0.05325741]
[[0.33333333 0.33333333 0.33333333]
 [0.60407835 0.22907601 0.16684557]]
[[0.         1.         0.        ]
 [0.33333333 0.33333333 0.33333333]]
value of table br policy [ 0.43723278 -0.43723278]
[[0.81925625 0.07688884 0.10385487]
 [0.33333333 0.33333333 0.33333333]]
value of hypernet br policy [-0.05631017  0.05631017]
[[0.81925625 0.07688884 0.10

  9%|▉         | 8764/100000 [01:19<13:11, 115.30it/s]

[[0.33333333 0.33333333 0.33333333]
 [0.53113818 0.33855021 0.13031167]]
[[0.         1.         0.        ]
 [0.33333333 0.33333333 0.33333333]]
value of table br policy [ 0.40082651 -0.40082651]
[[0.83601427 0.05037752 0.11360832]
 [0.33333333 0.33333333 0.33333333]]
value of hypernet br policy [-0.17577734  0.17577734]
[[0.83464551 0.05041549 0.11493899]
 [0.33333333 0.33333333 0.33333333]]
[[0.33333333 0.33333333 0.33333333]
 [0.         1.         0.        ]]
value of table br policy [-0.71970652  0.71970652]
[[0.33333333 0.33333333 0.33333333]
 [0.53296173 0.33648092 0.13055727]]
value of hypernet br policy [-0.17416914  0.17416914]
[[0.33333333 0.33333333 0.33333333]
 [0.53710288 0.33584443 0.12705261]]
[[0.         1.         0.        ]
 [0.33333333 0.33333333 0.33333333]]
value of table br policy [ 0.41005027 -0.41005027]
[[0.83542061 0.05185351 0.11272587]
 [0.33333333 0.33333333 0.33333333]]
value of hypernet br policy [-0.17585348  0.17585348]
[[0.83542061 0.05185351 0.11

  9%|▉         | 9004/100000 [01:21<13:15, 114.36it/s]

[[0.33333333 0.33333333 0.33333333]
 [0.57059795 0.28823686 0.14116524]]
[[0.         1.         0.        ]
 [0.33333333 0.33333333 0.33333333]]
value of table br policy [ 0.42943271 -0.42943271]
[[0.81728029 0.07049728 0.11222246]
 [0.33333333 0.33333333 0.33333333]]
value of hypernet br policy [-0.12161215  0.12161215]
[[0.81788087 0.07032008 0.11179909]
 [0.33333333 0.33333333 0.33333333]]
[[0.33333333 0.33333333 0.33333333]
 [0.         1.         0.        ]]
value of table br policy [-0.70608178  0.70608178]
[[0.33333333 0.33333333 0.33333333]
 [0.57132387 0.28702292 0.14165327]]
value of hypernet br policy [-0.12046517  0.12046517]
[[0.33333333 0.33333333 0.33333333]
 [0.56490052 0.29225826 0.14284118]]
[[0.         1.         0.        ]
 [0.33333333 0.33333333 0.33333333]]
value of table br policy [ 0.42205934 -0.42205934]
[[0.81784838 0.06858443 0.11356721]
 [0.33333333 0.33333333 0.33333333]]
value of hypernet br policy [-0.12421705  0.12421705]
[[0.81784838 0.06858443 0.11

  9%|▉         | 9266/100000 [01:24<13:14, 114.20it/s]

[[0.33333333 0.33333333 0.33333333]
 [0.52301466 0.35395339 0.12303197]]
[[0.         1.         0.        ]
 [0.33333333 0.33333333 0.33333333]]
value of table br policy [ 0.39998269 -0.39998269]
[[0.83085114 0.05362855 0.11552039]
 [0.33333333 0.33333333 0.33333333]]
value of hypernet br policy [-0.18994085  0.18994085]
[[0.83013999 0.0538283  0.11603171]
 [0.33333333 0.33333333 0.33333333]]
[[0.33333333 0.33333333 0.33333333]
 [0.         1.         0.        ]]
value of table br policy [-0.71410828  0.71410828]
[[0.33333333 0.33333333 0.33333333]
 [0.52282113 0.35423368 0.12294517]]
value of hypernet br policy [-0.1900387  0.1900387]
[[0.33333333 0.33333333 0.33333333]
 [0.52944386 0.34739396 0.12316219]]
[[0.         1.         0.        ]
 [0.33333333 0.33333333 0.33333333]]
value of table br policy [ 0.40628167 -0.40628167]
[[0.83026665 0.05522675 0.11450662]
 [0.33333333 0.33333333 0.33333333]]
value of hypernet br policy [-0.18458047  0.18458047]
[[0.83026665 0.05522675 0.1145

 10%|▉         | 9504/100000 [01:26<13:17, 113.52it/s]

[[0.33333333 0.33333333 0.33333333]
 [0.50281608 0.38476545 0.11241843]]
[[0.         1.         0.        ]
 [0.33333333 0.33333333 0.33333333]]
value of table br policy [ 0.39039765 -0.39039765]
[[0.83273435 0.04836246 0.11890315]
 [0.33333333 0.33333333 0.33333333]]
value of hypernet br policy [-0.22194872  0.22194872]
[[0.8331632  0.04821438 0.11862236]
 [0.33333333 0.33333333 0.33333333]]
[[0.33333333 0.33333333 0.33333333]
 [0.         1.         0.        ]]
value of table br policy [-0.71454084  0.71454084]
[[0.33333333 0.33333333 0.33333333]
 [0.50426513 0.38273823 0.11299662]]
value of hypernet br policy [-0.22028983  0.22028983]
[[0.33333333 0.33333333 0.33333333]
 [0.49814048 0.38579869 0.11606079]]
[[0.         1.         0.        ]
 [0.33333333 0.33333333 0.33333333]]
value of table br policy [ 0.3820797 -0.3820797]
[[0.83255726 0.04677361 0.1206691 ]
 [0.33333333 0.33333333 0.33333333]]
value of hypernet br policy [-0.22025719  0.22025719]
[[0.83255726 0.04677361 0.1206

 10%|▉         | 9754/100000 [01:28<13:18, 113.00it/s]

[[0.33333333 0.33333333 0.33333333]
 [0.52127153 0.35307041 0.12565817]]
[[0.         1.         0.        ]
 [0.33333333 0.33333333 0.33333333]]
value of table br policy [ 0.39561336 -0.39561336]
[[0.8249175  0.05649197 0.11859063]
 [0.33333333 0.33333333 0.33333333]]
value of hypernet br policy [-0.18519443  0.18519443]
[[0.82565671 0.05584428 0.11849899]
 [0.33333333 0.33333333 0.33333333]]
[[0.33333333 0.33333333 0.33333333]
 [0.         1.         0.        ]]
value of table br policy [-0.70715772  0.70715772]
[[0.33333333 0.33333333 0.33333333]
 [0.5211072  0.35410362 0.12478917]]
value of hypernet br policy [-0.18699268  0.18699268]
[[0.33333333 0.33333333 0.33333333]
 [0.52683806 0.34969056 0.12347141]]
[[0.         1.         0.        ]
 [0.33333333 0.33333333 0.33333333]]
value of table br policy [ 0.40336666 -0.40336666]
[[0.82640517 0.05715987 0.11643502]
 [0.33333333 0.33333333 0.33333333]]
value of hypernet br policy [-0.18451846  0.18451846]
[[0.82640517 0.05715987 0.11

 10%|█         | 10006/100000 [01:30<13:25, 111.74it/s]

[[0.33333333 0.33333333 0.33333333]
 [0.5125612  0.36575344 0.12168542]]
[[0.         1.         0.        ]
 [0.33333333 0.33333333 0.33333333]]
value of table br policy [ 0.39087578 -0.39087578]
[[0.82440233 0.05788448 0.11771317]
 [0.33333333 0.33333333 0.33333333]]
value of hypernet br policy [-0.19586581  0.19586581]
[[0.82412034 0.0578955  0.11798418]
 [0.33333333 0.33333333 0.33333333]]
[[0.33333333 0.33333333 0.33333333]
 [0.         1.         0.        ]]
value of table br policy [-0.70613617  0.70613617]
[[0.33333333 0.33333333 0.33333333]
 [0.51471961 0.36278659 0.12249374]]
value of hypernet br policy [-0.1932478  0.1932478]
[[0.33333333 0.33333333 0.33333333]
 [0.51608771 0.36260483 0.12130751]]
[[0.         1.         0.        ]
 [0.33333333 0.33333333 0.33333333]]
value of table br policy [ 0.3947802 -0.3947802]
[[0.82406372 0.05885592 0.11708024]
 [0.33333333 0.33333333 0.33333333]]
value of hypernet br policy [-0.19357902  0.19357902]
[[0.82406372 0.05885592 0.117080

 10%|█         | 10254/100000 [01:32<13:25, 111.44it/s]

[[0.33333333 0.33333333 0.33333333]
 [0.4967154  0.3898167  0.1134679 ]]
[[0.         1.         0.        ]
 [0.33333333 0.33333333 0.33333333]]
value of table br policy [ 0.38324749 -0.38324749]
[[0.8282879  0.05375604 0.11795614]
 [0.33333333 0.33333333 0.33333333]]
value of hypernet br policy [-0.22090386  0.22090386]
[[0.82618141 0.05373155 0.12008706]
 [0.33333333 0.33333333 0.33333333]]
[[0.33333333 0.33333333 0.33333333]
 [0.         1.         0.        ]]
value of table br policy [-0.70609435  0.70609435]
[[0.33333333 0.33333333 0.33333333]
 [0.50042212 0.38551578 0.11406203]]
value of hypernet br policy [-0.21730909  0.21730909]
[[0.33333333 0.33333333 0.33333333]
 [0.49839768 0.3884832  0.11311919]]
[[0.         1.         0.        ]
 [0.33333333 0.33333333 0.33333333]]
value of table br policy [ 0.38527849 -0.38527849]
[[0.82712764 0.05369827 0.11917409]
 [0.33333333 0.33333333 0.33333333]]
value of hypernet br policy [-0.22017135  0.22017135]
[[0.82712764 0.05369827 0.11

 11%|█         | 10519/100000 [01:34<12:46, 116.78it/s]

[[0.33333333 0.33333333 0.33333333]
 [0.48893061 0.40107149 0.10999791]]
[[0.         1.         0.        ]
 [0.33333333 0.33333333 0.33333333]]
value of table br policy [ 0.37893271 -0.37893271]
[[0.82440323 0.05026913 0.12532759]
 [0.33333333 0.33333333 0.33333333]]
value of hypernet br policy [-0.23192456  0.23192456]
[[0.82801449 0.04870511 0.12328044]
 [0.33333333 0.33333333 0.33333333]]
[[0.33333333 0.33333333 0.33333333]
 [0.         1.         0.        ]]
value of table br policy [-0.70473405  0.70473405]
[[0.33333333 0.33333333 0.33333333]
 [0.48627198 0.40594795 0.10778002]]
value of hypernet br policy [-0.23835526  0.23835526]
[[0.33333333 0.33333333 0.33333333]
 [0.48364076 0.4091863  0.10717294]]
[[0.         1.         0.        ]
 [0.33333333 0.33333333 0.33333333]]
value of table br policy [ 0.37646782 -0.37646782]
[[0.82898331 0.04767485 0.12334184]
 [0.33333333 0.33333333 0.33333333]]
value of hypernet br policy [-0.24159934  0.24159934]
[[0.82898331 0.04767485 0.12

 11%|█         | 10754/100000 [01:37<13:47, 107.86it/s]

[[0.33333333 0.33333333 0.33333333]
 [0.51610434 0.36184841 0.12204716]]
[[0.         1.         0.        ]
 [0.33333333 0.33333333 0.33333333]]
value of table br policy [ 0.39405718 -0.39405718]
[[0.81716293 0.05778403 0.12505302]
 [0.33333333 0.33333333 0.33333333]]
value of hypernet br policy [-0.19247665  0.19247665]
[[0.81621277 0.05774715 0.12604006]
 [0.33333333 0.33333333 0.33333333]]
[[0.33333333 0.33333333 0.33333333]
 [0.         1.         0.        ]]
value of table br policy [-0.69017272  0.69017272]
[[0.33333333 0.33333333 0.33333333]
 [0.5180335  0.35952967 0.12243677]]
value of hypernet br policy [-0.19065151  0.19065151]
[[0.33333333 0.33333333 0.33333333]
 [0.51920623 0.36057615 0.12021767]]
[[0.         1.         0.        ]
 [0.33333333 0.33333333 0.33333333]]
value of table br policy [ 0.39898856 -0.39898856]
[[0.81670946 0.05861434 0.12467625]
 [0.33333333 0.33333333 0.33333333]]
value of hypernet br policy [-0.192694  0.192694]
[[0.81670946 0.05861434 0.124676

 11%|█         | 11013/100000 [01:39<14:06, 105.18it/s]

[[0.33333333 0.33333333 0.33333333]
 [0.44353953 0.46103168 0.09542881]]
[[0.         1.         0.        ]
 [0.33333333 0.33333333 0.33333333]]
value of table br policy [ 0.34811072 -0.34811072]
[[0.82281929 0.04542068 0.13176003]
 [0.33333333 0.33333333 0.33333333]]
value of hypernet br policy [-0.2827089  0.2827089]
[[0.82393336 0.04483437 0.13123235]
 [0.33333333 0.33333333 0.33333333]]
[[0.33333333 0.33333333 0.33333333]
 [0.         1.         0.        ]]
value of table br policy [-0.69270101  0.69270101]
[[0.33333333 0.33333333 0.33333333]
 [0.44268799 0.46270114 0.09461091]]
value of hypernet br policy [-0.28504964  0.28504964]
[[0.33333333 0.33333333 0.33333333]
 [0.43939748 0.46685991 0.09374259]]
[[0.         1.         0.        ]
 [0.33333333 0.33333333 0.33333333]]
value of table br policy [ 0.3456549 -0.3456549]
[[0.82432836 0.04418832 0.13148338]
 [0.33333333 0.33333333 0.33333333]]
value of hypernet br policy [-0.28868643  0.28868643]
[[0.82432836 0.04418832 0.131483

 11%|█▏        | 11269/100000 [01:41<12:02, 122.77it/s]

[[0.33333333 0.33333333 0.33333333]
 [0.45793265 0.4455246  0.09654277]]
[[0.         1.         0.        ]
 [0.33333333 0.33333333 0.33333333]]
value of table br policy [ 0.36138988 -0.36138988]
[[0.82973224 0.04392404 0.12634374]
 [0.33333333 0.33333333 0.33333333]]
value of hypernet br policy [-0.27525546  0.27525546]
[[0.82969153 0.0445242  0.12578417]
 [0.33333333 0.33333333 0.33333333]]
[[0.33333333 0.33333333 0.33333333]
 [0.         1.         0.        ]]
value of table br policy [-0.70390736  0.70390736]
[[0.33333333 0.33333333 0.33333333]
 [0.45507541 0.44849187 0.09643278]]
value of hypernet br policy [-0.27696027  0.27696027]
[[0.33333333 0.33333333 0.33333333]
 [0.44992155 0.45149139 0.09858707]]
[[0.         1.         0.        ]
 [0.33333333 0.33333333 0.33333333]]
value of table br policy [ 0.35133447 -0.35133447]
[[0.82815409 0.04298654 0.12885936]
 [0.33333333 0.33333333 0.33333333]]
value of hypernet br policy [-0.27695421  0.27695421]
[[0.82815409 0.04298654 0.12

 12%|█▏        | 11504/100000 [01:43<13:39, 107.97it/s]

[[0.33333333 0.33333333 0.33333333]
 [0.49602446 0.39202014 0.11195543]]
[[0.         1.         0.        ]
 [0.33333333 0.33333333 0.33333333]]
value of table br policy [ 0.38406903 -0.38406903]
[[0.81760168 0.056178   0.12622036]
 [0.33333333 0.33333333 0.33333333]]
value of hypernet br policy [-0.2205326  0.2205326]
[[0.82174224 0.05507299 0.12318471]
 [0.33333333 0.33333333 0.33333333]]
[[0.33333333 0.33333333 0.33333333]
 [0.         1.         0.        ]]
value of table br policy [-0.69855753  0.69855753]
[[0.33333333 0.33333333 0.33333333]
 [0.49118644 0.39885324 0.10996024]]
value of hypernet br policy [-0.22777436  0.22777436]
[[0.33333333 0.33333333 0.33333333]
 [0.487459   0.40035513 0.11218592]]
[[0.         1.         0.        ]
 [0.33333333 0.33333333 0.33333333]]
value of table br policy [ 0.37527309 -0.37527309]
[[0.821383   0.05315769 0.12545928]
 [0.33333333 0.33333333 0.33333333]]
value of hypernet br policy [-0.22767663  0.22767663]
[[0.821383   0.05315769 0.1254

 12%|█▏        | 11755/100000 [01:45<13:16, 110.85it/s]

[[0.33333333 0.33333333 0.33333333]
 [0.52446336 0.35644123 0.11909537]]
[[0.         1.         0.        ]
 [0.33333333 0.33333333 0.33333333]]
value of table br policy [ 0.40536799 -0.40536799]
[[0.81228811 0.06158996 0.12612197]
 [0.33333333 0.33333333 0.33333333]]
value of hypernet br policy [-0.1890179  0.1890179]
[[0.81508321 0.06065654 0.12426025]
 [0.33333333 0.33333333 0.33333333]]
[[0.33333333 0.33333333 0.33333333]
 [0.         1.         0.        ]]
value of table br policy [-0.69082296  0.69082296]
[[0.33333333 0.33333333 0.33333333]
 [0.52308005 0.35867968 0.11824023]]
value of hypernet br policy [-0.19185041  0.19185041]
[[0.33333333 0.33333333 0.33333333]
 [0.52192926 0.35838321 0.1196875 ]]
[[0.         1.         0.        ]
 [0.33333333 0.33333333 0.33333333]]
value of table br policy [ 0.40224177 -0.40224177]
[[0.81505972 0.05990448 0.12503578]
 [0.33333333 0.33333333 0.33333333]]
value of hypernet br policy [-0.19090428  0.19090428]
[[0.81505972 0.05990448 0.1250

 12%|█▏        | 12011/100000 [01:48<13:29, 108.73it/s]

[[0.33333333 0.33333333 0.33333333]
 [0.4779318  0.41632324 0.10574504]]
[[0.         1.         0.        ]
 [0.33333333 0.33333333 0.33333333]]
value of table br policy [ 0.37218676 -0.37218676]
[[0.81925535 0.05115005 0.12959464]
 [0.33333333 0.33333333 0.33333333]]
value of hypernet br policy [-0.24338962  0.24338962]
[[0.82015687 0.05074597 0.12909719]
 [0.33333333 0.33333333 0.33333333]]
[[0.33333333 0.33333333 0.33333333]
 [0.         1.         0.        ]]
value of table br policy [-0.69105968  0.69105968]
[[0.33333333 0.33333333 0.33333333]
 [0.4793517  0.41462615 0.10602215]]
value of hypernet br policy [-0.24251461  0.24251461]
[[0.33333333 0.33333333 0.33333333]
 [0.48701826 0.40834764 0.10463411]]
[[0.         1.         0.        ]
 [0.33333333 0.33333333 0.33333333]]
value of table br policy [ 0.38238415 -0.38238415]
[[0.82069457 0.05289757 0.12640785]
 [0.33333333 0.33333333 0.33333333]]
value of hypernet br policy [-0.23897343  0.23897343]
[[0.82069457 0.05289757 0.12

 12%|█▏        | 12270/100000 [01:50<12:13, 119.61it/s]

[[0.33333333 0.33333333 0.33333333]
 [0.55949819 0.30496728 0.13553457]]
[[0.         1.         0.        ]
 [0.33333333 0.33333333 0.33333333]]
value of table br policy [ 0.42396362 -0.42396362]
[[0.80393511 0.07428336 0.12178152]
 [0.33333333 0.33333333 0.33333333]]
value of hypernet br policy [-0.13571663  0.13571663]
[[0.80023676 0.07527375 0.12448955]
 [0.33333333 0.33333333 0.33333333]]
[[0.33333333 0.33333333 0.33333333]
 [0.         1.         0.        ]]
value of table br policy [-0.67574722  0.67574722]
[[0.33333333 0.33333333 0.33333333]
 [0.5610401  0.30296865 0.13599129]]
value of hypernet br policy [-0.1337536  0.1337536]
[[0.33333333 0.33333333 0.33333333]
 [0.55814338 0.30500555 0.1368511 ]]
[[0.         1.         0.        ]
 [0.33333333 0.33333333 0.33333333]]
value of table br policy [ 0.42129228 -0.42129228]
[[0.80097753 0.07421471 0.12480775]
 [0.33333333 0.33333333 0.33333333]]
value of hypernet br policy [-0.13501541  0.13501541]
[[0.80097753 0.07421471 0.1248

 13%|█▎        | 12514/100000 [01:52<13:48, 105.63it/s]

[[0.33333333 0.33333333 0.33333333]
 [0.50162715 0.38367212 0.11470076]]
[[0.         1.         0.        ]
 [0.33333333 0.33333333 0.33333333]]
value of table br policy [ 0.38692639 -0.38692639]
[[0.81073558 0.05975054 0.12951389]
 [0.33333333 0.33333333 0.33333333]]
value of hypernet br policy [-0.21022241  0.21022241]
[[0.80912971 0.05963054 0.13123979]
 [0.33333333 0.33333333 0.33333333]]
[[0.33333333 0.33333333 0.33333333]
 [0.         1.         0.        ]]
value of table br policy [-0.67788993  0.67788993]
[[0.33333333 0.33333333 0.33333333]
 [0.50245667 0.38331574 0.11422767]]
value of hypernet br policy [-0.21021288  0.21021288]
[[0.33333333 0.33333333 0.33333333]
 [0.50344527 0.37997603 0.11657869]]
[[0.         1.         0.        ]
 [0.33333333 0.33333333 0.33333333]]
value of table br policy [ 0.38686658 -0.38686658]
[[0.8101964  0.05911569 0.13068792]
 [0.33333333 0.33333333 0.33333333]]
value of hypernet br policy [-0.20666963  0.20666963]
[[0.8101964  0.05911569 0.13

 13%|█▎        | 12763/100000 [01:54<13:10, 110.32it/s]

[[0.33333333 0.33333333 0.33333333]
 [0.47237563 0.41882572 0.10879868]]
[[0.         1.         0.        ]
 [0.33333333 0.33333333 0.33333333]]
value of table br policy [ 0.36357696 -0.36357696]
[[0.81548333 0.05442251 0.13009419]
 [0.33333333 0.33333333 0.33333333]]
value of hypernet br policy [-0.24000165  0.24000165]
[[0.81433749 0.05416471 0.13149783]
 [0.33333333 0.33333333 0.33333333]]
[[0.33333333 0.33333333 0.33333333]
 [0.         1.         0.        ]]
value of table br policy [-0.68283966  0.68283966]
[[0.33333333 0.33333333 0.33333333]
 [0.47510102 0.41582939 0.10906961]]
value of hypernet br policy [-0.2377741  0.2377741]
[[0.33333333 0.33333333 0.33333333]
 [0.4646045  0.4252528  0.11014272]]
[[0.         1.         0.        ]
 [0.33333333 0.33333333 0.33333333]]
value of table br policy [ 0.35446177 -0.35446177]
[[0.81465763 0.05175868 0.13358369]
 [0.33333333 0.33333333 0.33333333]]
value of hypernet br policy [-0.2436171  0.2436171]
[[0.81465763 0.05175868 0.133583

 13%|█▎        | 13014/100000 [01:57<12:37, 114.82it/s]

[[0.33333333 0.33333333 0.33333333]
 [0.32796279 0.61395431 0.05808293]]
[[0.         0.         1.        ]
 [0.33333333 0.33333333 0.33333333]]
value of table br policy [ 0.28599152 -0.28599152]
[[0.82674682 0.03137248 0.14188063]
 [0.33333333 0.33333333 0.33333333]]
value of hypernet br policy [-0.41052143  0.41052143]
[[0.83219534 0.03024508 0.13755958]
 [0.33333333 0.33333333 0.33333333]]
[[0.33333333 0.33333333 0.33333333]
 [0.         1.         0.        ]]
value of table br policy [-0.69463576  0.69463576]
[[0.33333333 0.33333333 0.33333333]
 [0.31690434 0.62826395 0.05483177]]
value of hypernet br policy [-0.42645069  0.42645069]
[[0.33333333 0.33333333 0.33333333]
 [0.31985575 0.62676901 0.05337525]]
[[0.         0.         1.        ]
 [0.33333333 0.33333333 0.33333333]]
value of table br policy [ 0.30691326 -0.30691326]
[[0.8333106  0.03012152 0.13656792]
 [0.33333333 0.33333333 0.33333333]]
value of hypernet br policy [-0.42787379  0.42787379]
[[0.8333106  0.03012152 0.13

 13%|█▎        | 13270/100000 [01:59<11:38, 124.15it/s]

[[0.33333333 0.33333333 0.33333333]
 [0.48569003 0.4039641  0.11034586]]
[[0.         1.         0.        ]
 [0.33333333 0.33333333 0.33333333]]
value of table br policy [ 0.37534417 -0.37534417]
[[0.81203568 0.05674198 0.1312224 ]
 [0.33333333 0.33333333 0.33333333]]
value of hypernet br policy [-0.22785499  0.22785499]
[[0.81326073 0.05660205 0.13013719]
 [0.33333333 0.33333333 0.33333333]]
[[0.33333333 0.33333333 0.33333333]
 [0.         1.         0.        ]]
value of table br policy [-0.68312354  0.68312354]
[[0.33333333 0.33333333 0.33333333]
 [0.48490605 0.40480986 0.11028405]]
value of hypernet br policy [-0.2287454  0.2287454]
[[0.33333333 0.33333333 0.33333333]
 [0.49070594 0.40033907 0.10895502]]
[[0.         1.         0.        ]
 [0.33333333 0.33333333 0.33333333]]
value of table br policy [ 0.38175092 -0.38175092]
[[0.81310207 0.05829209 0.12860586]
 [0.33333333 0.33333333 0.33333333]]
value of hypernet br policy [-0.22629362  0.22629362]
[[0.81310207 0.05829209 0.1286

 14%|█▎        | 13520/100000 [02:01<11:38, 123.80it/s]

[[0.33333333 0.33333333 0.33333333]
 [0.49324131 0.39008781 0.11667082]]
[[0.         1.         0.        ]
 [0.33333333 0.33333333 0.33333333]]
value of table br policy [ 0.37657049 -0.37657049]
[[0.80469036 0.06331255 0.13199705]
 [0.33333333 0.33333333 0.33333333]]
value of hypernet br policy [-0.20979033  0.20979033]
[[0.80449736 0.06304634 0.13245636]
 [0.33333333 0.33333333 0.33333333]]
[[0.33333333 0.33333333 0.33333333]
 [0.         1.         0.        ]]
value of table br policy [-0.672041  0.672041]
[[0.33333333 0.33333333 0.33333333]
 [0.49463454 0.38858774 0.11677773]]
value of hypernet br policy [-0.20889452  0.20889452]
[[0.33333333 0.33333333 0.33333333]
 [0.49880844 0.38331407 0.11787742]]
[[0.         1.         0.        ]
 [0.33333333 0.33333333 0.33333333]]
value of table br policy [ 0.38093103 -0.38093103]
[[0.80505866 0.06399644 0.13094486]
 [0.33333333 0.33333333 0.33333333]]
value of hypernet br policy [-0.20443724  0.20443724]
[[0.80505866 0.06399644 0.130944

 14%|█▍        | 13766/100000 [02:03<12:53, 111.52it/s]

[[0.33333333 0.33333333 0.33333333]
 [0.42258012 0.48910028 0.08831961]]
[[0.         1.         0.        ]
 [0.33333333 0.33333333 0.33333333]]
value of table br policy [ 0.33426051 -0.33426051]
[[0.81188607 0.04630782 0.14180613]
 [0.33333333 0.33333333 0.33333333]]
value of hypernet br policy [-0.3004764  0.3004764]
[[0.81669599 0.04531925 0.13798469]
 [0.33333333 0.33333333 0.33333333]]
[[0.33333333 0.33333333 0.33333333]
 [0.         1.         0.        ]]
value of table br policy [-0.6787113  0.6787113]
[[0.33333333 0.33333333 0.33333333]
 [0.41203752 0.50321674 0.08474574]]
value of hypernet br policy [-0.31434963  0.31434963]
[[0.33333333 0.33333333 0.33333333]
 [0.41274834 0.50349987 0.08375177]]
[[0.         1.         0.        ]
 [0.33333333 0.33333333 0.33333333]]
value of table br policy [ 0.32899657 -0.32899657]
[[0.81618845 0.04459196 0.13921952]
 [0.33333333 0.33333333 0.33333333]]
value of hypernet br policy [-0.31528856  0.31528856]
[[0.81618845 0.04459196 0.139219

 14%|█▍        | 14013/100000 [02:05<12:59, 110.32it/s]

[[0.33333333 0.33333333 0.33333333]
 [0.40141562 0.51879942 0.07978494]]
[[0.         1.         0.        ]
 [0.33333333 0.33333333 0.33333333]]
value of table br policy [ 0.32163067 -0.32163067]
[[0.81220609 0.04410161 0.14369233]
 [0.33333333 0.33333333 0.33333333]]
value of hypernet br policy [-0.32551865  0.32551865]
[[0.80870485 0.0446922  0.14660305]
 [0.33333333 0.33333333 0.33333333]]
[[0.33333333 0.33333333 0.33333333]
 [0.         1.         0.        ]]
value of table br policy [-0.66210181  0.66210181]
[[0.33333333 0.33333333 0.33333333]
 [0.40451428 0.51481903 0.08066672]]
value of hypernet br policy [-0.32045661  0.32045661]
[[0.33333333 0.33333333 0.33333333]
 [0.41363242 0.50596344 0.08040413]]
[[0.         1.         0.        ]
 [0.33333333 0.33333333 0.33333333]]
value of table br policy [ 0.33322829 -0.33322829]
[[0.81034791 0.04678154 0.14287053]
 [0.33333333 0.33333333 0.33333333]]
value of hypernet br policy [-0.31607079  0.31607079]
[[0.81034791 0.04678154 0.14

 14%|█▍        | 14264/100000 [02:08<12:48, 111.55it/s]

[[0.33333333 0.33333333 0.33333333]
 [0.50614303 0.373741   0.12011594]]
[[0.         1.         0.        ]
 [0.33333333 0.33333333 0.33333333]]
value of table br policy [ 0.3860271 -0.3860271]
[[0.79788893 0.06602955 0.13608147]
 [0.33333333 0.33333333 0.33333333]]
value of hypernet br policy [-0.1948929  0.1948929]
[[0.79902679 0.06598352 0.13498977]
 [0.33333333 0.33333333 0.33333333]]
[[0.33333333 0.33333333 0.33333333]
 [0.         1.         0.        ]]
value of table br policy [-0.66403702  0.66403702]
[[0.33333333 0.33333333 0.33333333]
 [0.50276095 0.37822586 0.11901321]]
value of hypernet br policy [-0.19860779  0.19860779]
[[0.33333333 0.33333333 0.33333333]
 [0.50048953 0.37892991 0.12058054]]
[[0.         1.         0.        ]
 [0.33333333 0.33333333 0.33333333]]
value of table br policy [ 0.37990899 -0.37990899]
[[0.79857093 0.06452832 0.13690081]
 [0.33333333 0.33333333 0.33333333]]
value of hypernet br policy [-0.19843702  0.19843702]
[[0.79857093 0.06452832 0.136900

 15%|█▍        | 14507/100000 [02:10<12:24, 114.87it/s]

[[0.33333333 0.33333333 0.33333333]
 [0.54153711 0.3240183  0.13444461]]
[[0.         1.         0.        ]
 [0.33333333 0.33333333 0.33333333]]
value of table br policy [ 0.4070925 -0.4070925]
[[0.78985435 0.08084148 0.12930411]
 [0.33333333 0.33333333 0.33333333]]
value of hypernet br policy [-0.14495172  0.14495172]
[[0.78843868 0.08206745 0.12949391]
 [0.33333333 0.33333333 0.33333333]]
[[0.33333333 0.33333333 0.33333333]
 [0.         1.         0.        ]]
value of table br policy [-0.65894477  0.65894477]
[[0.33333333 0.33333333 0.33333333]
 [0.54144907 0.32291603 0.13563493]]
value of hypernet br policy [-0.14265423  0.14265423]
[[0.33333333 0.33333333 0.33333333]
 [0.53954679 0.32455984 0.13589342]]
[[0.         1.         0.        ]
 [0.33333333 0.33333333 0.33333333]]
value of table br policy [ 0.40365337 -0.40365337]
[[0.78769684 0.08166575 0.13063742]
 [0.33333333 0.33333333 0.33333333]]
value of hypernet br policy [-0.14373263  0.14373263]
[[0.78769684 0.08166575 0.1306

 15%|█▍        | 14751/100000 [02:12<11:59, 118.44it/s]

[[0.33333333 0.33333333 0.33333333]
 [0.55110258 0.3081952  0.14070213]]
[[0.         1.         0.        ]
 [0.33333333 0.33333333 0.33333333]]
value of table br policy [ 0.41040045 -0.41040045]
[[0.78916472 0.08474414 0.12609111]
 [0.33333333 0.33333333 0.33333333]]
value of hypernet br policy [-0.12802905  0.12802905]
[[0.78747624 0.08536816 0.12715559]
 [0.33333333 0.33333333 0.33333333]]
[[0.33333333 0.33333333 0.33333333]
 [0.         1.         0.        ]]
value of table br policy [-0.66032065  0.66032065]
[[0.33333333 0.33333333 0.33333333]
 [0.55142659 0.30758819 0.14098522]]
value of hypernet br policy [-0.12716267  0.12716267]
[[0.33333333 0.33333333 0.33333333]
 [0.55332774 0.30623463 0.14043763]]
[[0.         1.         0.        ]
 [0.33333333 0.33333333 0.33333333]]
value of table br policy [ 0.41289011 -0.41289011]
[[0.78748882 0.08612279 0.1263884 ]
 [0.33333333 0.33333333 0.33333333]]
value of hypernet br policy [-0.12623374  0.12623374]
[[0.78748882 0.08612279 0.12

 15%|█▌        | 15005/100000 [02:14<12:27, 113.65it/s]

[[0.33333333 0.33333333 0.33333333]
 [0.56093293 0.30004066 0.1390264 ]]
[[0.         1.         0.        ]
 [0.33333333 0.33333333 0.33333333]]
value of table br policy [ 0.42190653 -0.42190653]
[[0.7833885  0.09385111 0.12276038]
 [0.33333333 0.33333333 0.33333333]]
value of hypernet br policy [-0.11856755  0.11856755]
[[0.78085363 0.09421639 0.12493004]
 [0.33333333 0.33333333 0.33333333]]
[[0.33333333 0.33333333 0.33333333]
 [0.         1.         0.        ]]
value of table br policy [-0.65592359  0.65592359]
[[0.33333333 0.33333333 0.33333333]
 [0.56649536 0.29227519 0.1412295 ]]
value of hypernet br policy [-0.1121359  0.1121359]
[[0.33333333 0.33333333 0.33333333]
 [0.56155878 0.29678494 0.14165628]]
[[0.         1.         0.        ]
 [0.33333333 0.33333333 0.33333333]]
value of table br policy [ 0.4199025 -0.4199025]
[[0.78178412 0.0934466  0.12476921]
 [0.33333333 0.33333333 0.33333333]]
value of hypernet br policy [-0.11507428  0.11507428]
[[0.78178412 0.0934466  0.124769

 15%|█▌        | 15258/100000 [02:16<13:37, 103.62it/s]

[[0.33333333 0.33333333 0.33333333]
 [0.56398541 0.29289913 0.14311543]]
[[0.         1.         0.        ]
 [0.33333333 0.33333333 0.33333333]]
value of table br policy [ 0.42086998 -0.42086998]
[[0.77808189 0.09604238 0.12587573]
 [0.33333333 0.33333333 0.33333333]]
value of hypernet br policy [-0.11024581  0.11024581]
[[0.78470987 0.09391098 0.12137913]
 [0.33333333 0.33333333 0.33333333]]
[[0.33333333 0.33333333 0.33333333]
 [0.         1.         0.        ]]
value of table br policy [-0.66333074  0.66333074]
[[0.33333333 0.33333333 0.33333333]
 [0.55538309 0.30588654 0.13873044]]
value of hypernet br policy [-0.12232446  0.12232446]
[[0.33333333 0.33333333 0.33333333]
 [0.55875266 0.30280504 0.13844228]]
[[0.         1.         0.        ]
 [0.33333333 0.33333333 0.33333333]]
value of table br policy [ 0.42031038 -0.42031038]
[[0.78374708 0.09344184 0.12281108]
 [0.33333333 0.33333333 0.33333333]]
value of hypernet br policy [-0.12097746  0.12097746]
[[0.78374708 0.09344184 0.12

 16%|█▌        | 15513/100000 [02:19<13:00, 108.31it/s]

[[0.33333333 0.33333333 0.33333333]
 [0.5505662  0.3150717  0.13436213]]
[[0.         1.         0.        ]
 [0.33333333 0.33333333 0.33333333]]
value of table br policy [ 0.41620407 -0.41620407]
[[0.78219414 0.09267726 0.12512864]
 [0.33333333 0.33333333 0.33333333]]
value of hypernet br policy [-0.13224442  0.13224442]
[[0.77858257 0.09243789 0.12897955]
 [0.33333333 0.33333333 0.33333333]]
[[0.33333333 0.33333333 0.33333333]
 [0.         1.         0.        ]]
value of table br policy [-0.64960302  0.64960302]
[[0.33333333 0.33333333 0.33333333]
 [0.55659693 0.30808571 0.13531731]]
value of hypernet br policy [-0.12762513  0.12762513]
[[0.33333333 0.33333333 0.33333333]
 [0.54511565 0.3194795  0.13540487]]
[[0.         1.         0.        ]
 [0.33333333 0.33333333 0.33333333]]
value of table br policy [ 0.40971078 -0.40971078]
[[0.78086662 0.08895149 0.13018192]
 [0.33333333 0.33333333 0.33333333]]
value of hypernet br policy [-0.1366671  0.1366671]
[[0.78086662 0.08895149 0.1301

 16%|█▌        | 15765/100000 [02:21<13:20, 105.24it/s]

[[0.33333333 0.33333333 0.33333333]
 [0.55065978 0.30775994 0.14158024]]
[[0.         1.         0.        ]
 [0.33333333 0.33333333 0.33333333]]
value of table br policy [ 0.40907954 -0.40907954]
[[0.77140945 0.10003293 0.12855765]
 [0.33333333 0.33333333 0.33333333]]
value of hypernet br policy [-0.1184978  0.1184978]
[[0.77510989 0.09909091 0.12579919]
 [0.33333333 0.33333333 0.33333333]]
[[0.33333333 0.33333333 0.33333333]
 [0.         1.         0.        ]]
value of table br policy [-0.64931069  0.64931069]
[[0.33333333 0.33333333 0.33333333]
 [0.54698437 0.31290987 0.14010577]]
value of hypernet br policy [-0.12307058  0.12307058]
[[0.33333333 0.33333333 0.33333333]
 [0.54963779 0.31112373 0.13923851]]
[[0.         1.         0.        ]
 [0.33333333 0.33333333 0.33333333]]
value of table br policy [ 0.41039929 -0.41039929]
[[0.77398336 0.09984388 0.12617271]
 [0.33333333 0.33333333 0.33333333]]
value of hypernet br policy [-0.12215441  0.12215441]
[[0.77398336 0.09984388 0.1261

 16%|█▌        | 16013/100000 [02:23<13:06, 106.76it/s]

[[0.33333333 0.33333333 0.33333333]
 [0.55460083 0.30126837 0.1441308 ]]
[[0.         1.         0.        ]
 [0.33333333 0.33333333 0.33333333]]
value of table br policy [ 0.41047004 -0.41047004]
[[0.76827919 0.10641444 0.12530632]
 [0.33333333 0.33333333 0.33333333]]
value of hypernet br policy [-0.10878975  0.10878975]
[[0.76133901 0.10846612 0.13019492]
 [0.33333333 0.33333333 0.33333333]]
[[0.33333333 0.33333333 0.33333333]
 [0.         1.         0.        ]]
value of table br policy [-0.63114409  0.63114409]
[[0.33333333 0.33333333 0.33333333]
 [0.56093454 0.29194584 0.14711963]]
value of hypernet br policy [-0.10039791  0.10039791]
[[0.33333333 0.33333333 0.33333333]
 [0.55993038 0.29314789 0.14692174]]
[[0.         1.         0.        ]
 [0.33333333 0.33333333 0.33333333]]
value of table br policy [ 0.41300865 -0.41300865]
[[0.76268578 0.10911072 0.12820348]
 [0.33333333 0.33333333 0.33333333]]
value of hypernet br policy [-0.10066338  0.10066338]
[[0.76268578 0.10911072 0.12

 16%|█▋        | 16263/100000 [02:25<13:27, 103.66it/s]

[[0.33333333 0.33333333 0.33333333]
 [0.59622252 0.22670378 0.1770736 ]]
[[0.         1.         0.        ]
 [0.33333333 0.33333333 0.33333333]]
value of table br policy [ 0.41914892 -0.41914892]
[[0.75290751 0.13166758 0.11542484]
 [0.33333333 0.33333333 0.33333333]]
value of hypernet br policy [-0.02483025  0.02483025]
[[0.74670935 0.13323995 0.12005073]
 [0.33333333 0.33333333 0.33333333]]
[[0.33333333 0.33333333 0.33333333]
 [0.         1.         0.        ]]
value of table br policy [-0.62665862  0.62665862]
[[0.33333333 0.33333333 0.33333333]
 [0.60204577 0.21816133 0.17979293]]
value of hypernet br policy [-0.0184747  0.0184747]
[[0.33333333 0.33333333 0.33333333]
 [0.60303205 0.21639593 0.18057205]]
[[0.         1.         0.        ]
 [0.33333333 0.33333333 0.33333333]]
value of table br policy [ 0.42246 -0.42246]
[[0.74805456 0.13503657 0.11690892]
 [0.33333333 0.33333333 0.33333333]]
value of hypernet br policy [-0.01495188  0.01495188]
[[0.74805456 0.13503657 0.11690892]


 17%|█▋        | 16506/100000 [02:27<12:06, 114.99it/s]

[[0.33333333 0.33333333 0.33333333]
 [0.59937131 0.22743739 0.17319128]]
[[0.         1.         0.        ]
 [0.33333333 0.33333333 0.33333333]]
value of table br policy [ 0.42618003 -0.42618003]
[[0.74945486 0.13543406 0.11511105]
 [0.33333333 0.33333333 0.33333333]]
value of hypernet br policy [-0.02574942  0.02574942]
[[0.75286317 0.13482571 0.11231106]
 [0.33333333 0.33333333 0.33333333]]
[[0.33333333 0.33333333 0.33333333]
 [0.         1.         0.        ]]
value of table br policy [-0.64055211  0.64055211]
[[0.33333333 0.33333333 0.33333333]
 [0.59556854 0.23259078 0.17184067]]
value of hypernet br policy [-0.02937353  0.02937353]
[[0.33333333 0.33333333 0.33333333]
 [0.59714055 0.23153536 0.17132404]]
[[0.         1.         0.        ]
 [0.33333333 0.33333333 0.33333333]]
value of table br policy [ 0.42581651 -0.42581651]
[[0.75144786 0.13507529 0.11347686]
 [0.33333333 0.33333333 0.33333333]]
value of hypernet br policy [-0.02921611  0.02921611]
[[0.75144786 0.13507529 0.11

 17%|█▋        | 16763/100000 [02:30<13:12, 105.07it/s]

[[0.33333333 0.33333333 0.33333333]
 [0.57204652 0.27030945 0.15764397]]
[[0.         1.         0.        ]
 [0.33333333 0.33333333 0.33333333]]
value of table br policy [ 0.41440254 -0.41440254]
[[0.76081759 0.11898654 0.12019582]
 [0.33333333 0.33333333 0.33333333]]
value of hypernet br policy [-0.07267708  0.07267708]
[[0.76456779 0.11696599 0.11846613]
 [0.33333333 0.33333333 0.33333333]]
[[0.33333333 0.33333333 0.33333333]
 [0.         1.         0.        ]]
value of table br policy [-0.64610166  0.64610166]
[[0.33333333 0.33333333 0.33333333]
 [0.56934112 0.27563891 0.15501992]]
value of hypernet br policy [-0.07855366  0.07855366]
[[0.33333333 0.33333333 0.33333333]
 [0.57213706 0.27246466 0.15539828]]
[[0.         1.         0.        ]
 [0.33333333 0.33333333 0.33333333]]
value of table br policy [ 0.41673878 -0.41673878]
[[0.76455307 0.11723816 0.1182088 ]
 [0.33333333 0.33333333 0.33333333]]
value of hypernet br policy [-0.07606969  0.07606969]
[[0.76455307 0.11723816 0.11

 17%|█▋        | 17019/100000 [02:32<11:29, 120.27it/s]

[[0.33333333 0.33333333 0.33333333]
 [0.58672899 0.2427673  0.17050371]]
[[0.         1.         0.        ]
 [0.33333333 0.33333333 0.33333333]]
value of table br policy [ 0.41622528 -0.41622528]
[[0.74254566 0.13929109 0.11816328]
 [0.33333333 0.33333333 0.33333333]]
value of hypernet br policy [-0.03632619  0.03632619]
[[0.73887306 0.14037912 0.12074771]
 [0.33333333 0.33333333 0.33333333]]
[[0.33333333 0.33333333 0.33333333]
 [0.         1.         0.        ]]
value of table br policy [-0.61812536  0.61812536]
[[0.33333333 0.33333333 0.33333333]
 [0.58939666 0.23889008 0.17171329]]
value of hypernet br policy [-0.03332396  0.03332396]
[[0.33333333 0.33333333 0.33333333]
 [0.59713984 0.23239204 0.17046814]]
[[0.         1.         0.        ]
 [0.33333333 0.33333333 0.33333333]]
value of table br policy [ 0.4266717 -0.4266717]
[[0.73806238 0.14537181 0.11656579]
 [0.33333333 0.33333333 0.33333333]]
value of hypernet br policy [-0.02619478  0.02619478]
[[0.73806238 0.14537181 0.1165

 17%|█▋        | 17255/100000 [02:34<12:06, 113.85it/s]

[[0.33333333 0.33333333 0.33333333]
 [0.60727346 0.21152356 0.18120302]]
[[0.         1.         0.        ]
 [0.33333333 0.33333333 0.33333333]]
value of table br policy [ 0.42607044 -0.42607044]
[[0.72525477 0.15970457 0.1150406 ]
 [0.33333333 0.33333333 0.33333333]]
value of hypernet br policy [ 0.00052797 -0.00052797]
[[0.72034818 0.16236216 0.11728963]
 [0.33333333 0.33333333 0.33333333]]
[[0.33333333 0.33333333 0.33333333]
 [0.         1.         0.        ]]
value of table br policy [-0.60305855  0.60305855]
[[0.33333333 0.33333333 0.33333333]
 [0.60956055 0.20641743 0.18402205]]
value of hypernet br policy [ 0.00567437 -0.00567437]
[[0.33333333 0.33333333 0.33333333]
 [0.61510485 0.20219527 0.18269992]]
[[0.         1.         0.        ]
 [0.33333333 0.33333333 0.33333333]]
value of table br policy [ 0.43240494 -0.43240494]
[[0.71870637 0.16728199 0.11401166]
 [0.33333333 0.33333333 0.33333333]]
value of hypernet br policy [ 0.01124561 -0.01124561]
[[0.71870637 0.16728199 0.11

 18%|█▊        | 17503/100000 [02:36<12:35, 109.22it/s]

[[0.33333333 0.33333333 0.33333333]
 [0.60880309 0.20744602 0.18375091]]
[[0.         1.         0.        ]
 [0.33333333 0.33333333 0.33333333]]
value of table br policy [ 0.42505218 -0.42505218]
[[0.71654564 0.16911013 0.11434421]
 [0.33333333 0.33333333 0.33333333]]
value of hypernet br policy [ 0.00900915 -0.00900915]
[[0.71330726 0.17092834 0.11576439]
 [0.33333333 0.33333333 0.33333333]]
[[0.33333333 0.33333333 0.33333333]
 [0.         1.         0.        ]]
value of table br policy [-0.59754287  0.59754287]
[[0.33333333 0.33333333 0.33333333]
 [0.61080164 0.20309664 0.18610169]]
value of hypernet br policy [ 0.01327291 -0.01327291]
[[0.33333333 0.33333333 0.33333333]
 [0.61211127 0.20218934 0.18569939]]
[[0.         1.         0.        ]
 [0.33333333 0.33333333 0.33333333]]
value of table br policy [ 0.42641188 -0.42641188]
[[0.71270561 0.1729774  0.11431699]
 [0.33333333 0.33333333 0.33333333]]
value of hypernet br policy [ 0.0151461 -0.0151461]
[[0.71270561 0.1729774  0.1143

 18%|█▊        | 17756/100000 [02:39<11:57, 114.66it/s]

[[0.33333333 0.33333333 0.33333333]
 [0.59860301 0.21761973 0.18377724]]
[[0.         1.         0.        ]
 [0.33333333 0.33333333 0.33333333]]
value of table br policy [ 0.41482577 -0.41482577]
[[0.72080249 0.16522764 0.11396986]
 [0.33333333 0.33333333 0.33333333]]
value of hypernet br policy [ 0.00072632 -0.00072632]
[[0.71436125 0.16881955 0.11681911]
 [0.33333333 0.33333333 0.33333333]]
[[0.33333333 0.33333333 0.33333333]
 [0.         1.         0.        ]]
value of table br policy [-0.59754214  0.59754214]
[[0.33333333 0.33333333 0.33333333]
 [0.60137928 0.21121021 0.18741059]]
value of hypernet br policy [ 0.00730528 -0.00730528]
[[0.33333333 0.33333333 0.33333333]
 [0.5974443  0.21499667 0.18755907]]
[[0.         1.         0.        ]
 [0.33333333 0.33333333 0.33333333]]
value of table br policy [ 0.40988523 -0.40988523]
[[0.71551806 0.16733609 0.11714586]
 [0.33333333 0.33333333 0.33333333]]
value of hypernet br policy [ 0.00415434 -0.00415434]
[[0.71551806 0.16733609 0.11

 18%|█▊        | 18005/100000 [02:41<12:20, 110.73it/s]

[[0.33333333 0.33333333 0.33333333]
 [0.61339152 0.19389872 0.19270979]]
[[0.         1.         0.        ]
 [0.33333333 0.33333333 0.33333333]]
value of table br policy [ 0.42068173 -0.42068173]
[[0.69983315 0.18944551 0.1107214 ]
 [0.33333333 0.33333333 0.33333333]]
value of hypernet br policy [ 0.03241738 -0.03241738]
[[0.69941956 0.19010253 0.11047795]
 [0.33333333 0.33333333 0.33333333]]
[[0.33333333 0.33333333 0.33333333]
 [0.         1.         0.        ]]
value of table br policy [-0.58894161  0.58894161]
[[0.33333333 0.33333333 0.33333333]
 [0.6128549  0.19409014 0.193055  ]]
value of hypernet br policy [ 0.03281676 -0.03281676]
[[0.33333333 0.33333333 0.33333333]
 [0.61801469 0.19111909 0.19086625]]
[[0.         1.         0.        ]
 [0.33333333 0.33333333 0.33333333]]
value of table br policy [ 0.42714845 -0.42714845]
[[0.69686985 0.19439135 0.10873879]
 [0.33333333 0.33333333 0.33333333]]
value of hypernet br policy [ 0.03643766 -0.03643766]
[[0.69686985 0.19439135 0.10

 18%|█▊        | 18255/100000 [02:43<12:35, 108.24it/s]

[[0.33333333 0.33333333 0.33333333]
 [0.61846721 0.19112037 0.1904124 ]]
[[0.         1.         0.        ]
 [0.33333333 0.33333333 0.33333333]]
value of table br policy [ 0.42805481 -0.42805481]
[[0.70168531 0.1877093  0.11060541]
 [0.33333333 0.33333333 0.33333333]]
value of hypernet br policy [ 0.03258622 -0.03258622]
[[0.69812691 0.19027007 0.11160304]
 [0.33333333 0.33333333 0.33333333]]
[[0.33333333 0.33333333 0.33333333]
 [0.         1.         0.        ]]
value of table br policy [-0.58652388  0.58652388]
[[0.33333333 0.33333333 0.33333333]
 [0.61959523 0.18722747 0.19317734]]
value of hypernet br policy [ 0.03703477 -0.03703477]
[[0.33333333 0.33333333 0.33333333]
 [0.62054867 0.18625511 0.19319622]]
[[0.         1.         0.        ]
 [0.33333333 0.33333333 0.33333333]]
value of table br policy [ 0.42735244 -0.42735244]
[[0.69727862 0.19212517 0.1105963 ]
 [0.33333333 0.33333333 0.33333333]]
value of hypernet br policy [ 0.03891379 -0.03891379]
[[0.69727862 0.19212517 0.11

 19%|█▊        | 18506/100000 [02:45<11:56, 113.81it/s]

[[0.33333333 0.33333333 0.33333333]
 [0.61336297 0.19875163 0.18788546]]
[[0.         1.         0.        ]
 [0.33333333 0.33333333 0.33333333]]
value of table br policy [ 0.4254775 -0.4254775]
[[0.69461924 0.1922631  0.11311772]
 [0.33333333 0.33333333 0.33333333]]
value of hypernet br policy [ 0.02735588 -0.02735588]
[[0.69627219 0.19216795 0.11155984]
 [0.33333333 0.33333333 0.33333333]]
[[0.33333333 0.33333333 0.33333333]
 [0.         1.         0.        ]]
value of table br policy [-0.58471236  0.58471236]
[[0.33333333 0.33333333 0.33333333]
 [0.61154008 0.20094335 0.18751654]]
value of hypernet br policy [ 0.02632892 -0.02632892]
[[0.33333333 0.33333333 0.33333333]
 [0.60960793 0.20258842 0.1878037 ]]
[[0.         1.         0.        ]
 [0.33333333 0.33333333 0.33333333]]
value of table br policy [ 0.42180423 -0.42180423]
[[0.69630826 0.19033511 0.11335658]
 [0.33333333 0.33333333 0.33333333]]
value of hypernet br policy [ 0.02385109 -0.02385109]
[[0.69630826 0.19033511 0.1133

 19%|█▉        | 18754/100000 [02:47<11:50, 114.43it/s]

[[0.33333333 0.33333333 0.33333333]
 [0.60580629 0.19902655 0.19516714]]
[[0.         1.         0.        ]
 [0.33333333 0.33333333 0.33333333]]
value of table br policy [ 0.41063915 -0.41063915]
[[0.69992816 0.18840839 0.11166345]
 [0.33333333 0.33333333 0.33333333]]
value of hypernet br policy [ 0.02924412 -0.02924412]
[[0.69617927 0.19124368 0.11257703]
 [0.33333333 0.33333333 0.33333333]]
[[0.33333333 0.33333333 0.33333333]
 [0.         1.         0.        ]]
value of table br policy [-0.58360224  0.58360224]
[[0.33333333 0.33333333 0.33333333]
 [0.6067028  0.19518691 0.19811024]]
value of hypernet br policy [ 0.03384867 -0.03384867]
[[0.33333333 0.33333333 0.33333333]
 [0.6007328  0.20051739 0.19874987]]
[[0.         1.         0.        ]
 [0.33333333 0.33333333 0.33333333]]
value of table br policy [ 0.40198293 -0.40198293]
[[0.69771153 0.18762085 0.11466754]
 [0.33333333 0.33333333 0.33333333]]
value of hypernet br policy [ 0.02829544 -0.02829544]
[[0.69771153 0.18762085 0.11

 19%|█▉        | 19000/100000 [02:49<10:56, 123.35it/s]

[[0.33333333 0.33333333 0.33333333]
 [0.58942449 0.23292015 0.17765534]]
[[0.         1.         0.        ]
 [0.33333333 0.33333333 0.33333333]]
value of table br policy [ 0.41176915 -0.41176915]
[[0.70714021 0.17519635 0.11766342]
 [0.33333333 0.33333333 0.33333333]]
value of hypernet br policy [-0.00888704  0.00888704]


 19%|█▉        | 19013/100000 [02:50<20:52, 64.67it/s] 

[[0.70050406 0.1781188  0.12137716]
 [0.33333333 0.33333333 0.33333333]]
[[0.33333333 0.33333333 0.33333333]
 [0.         1.         0.        ]]
value of table br policy [-0.5791269  0.5791269]
[[0.33333333 0.33333333 0.33333333]
 [0.59360898 0.22540228 0.18098873]]
value of hypernet br policy [-0.00230834  0.00230834]
[[0.33333333 0.33333333 0.33333333]
 [0.591259   0.22691701 0.18182392]]
[[0.         1.         0.        ]
 [0.33333333 0.33333333 0.33333333]]
value of table br policy [ 0.40943508 -0.40943508]
[[0.70204633 0.17759727 0.12035633]
 [0.33333333 0.33333333 0.33333333]]
value of hypernet br policy [-0.00279375  0.00279375]
[[0.70204633 0.17759727 0.12035633]
 [0.33333333 0.33333333 0.33333333]]
[[0.33333333 0.33333333 0.33333333]
 [0.         1.         0.        ]]
value of table br policy [-0.58169001  0.58169001]
[[0.33333333 0.33333333 0.33333333]
 [0.59532475 0.22357416 0.18110107]]
value of hypernet br policy [-0.00099562  0.00099562]


 19%|█▉        | 19255/100000 [02:52<12:45, 105.44it/s]

[[0.33333333 0.33333333 0.33333333]
 [0.59796637 0.21407466 0.18795888]]
[[0.         1.         0.        ]
 [0.33333333 0.33333333 0.33333333]]
value of table br policy [ 0.41000749 -0.41000749]
[[0.70097804 0.18290193 0.11612003]
 [0.33333333 0.33333333 0.33333333]]
value of hypernet br policy [ 0.01210706 -0.01210706]
[[0.6970309  0.1845396  0.11842952]
 [0.33333333 0.33333333 0.33333333]]
[[0.33333333 0.33333333 0.33333333]
 [0.         1.         0.        ]]
value of table br policy [-0.57860138  0.57860138]
[[0.33333333 0.33333333 0.33333333]
 [0.60014606 0.2102506  0.18960337]]
value of hypernet br policy [ 0.0151945 -0.0151945]
[[0.33333333 0.33333333 0.33333333]
 [0.59371579 0.2140564  0.19222778]]
[[0.         1.         0.        ]
 [0.33333333 0.33333333 0.33333333]]
value of table br policy [ 0.40148801 -0.40148801]
[[0.70010781 0.18001488 0.11987726]
 [0.33333333 0.33333333 0.33333333]]
value of hypernet br policy [ 0.0114789 -0.0114789]
[[0.70010781 0.18001488 0.119877

 20%|█▉        | 19516/100000 [02:54<11:42, 114.55it/s]

[[0.33333333 0.33333333 0.33333333]
 [0.61176616 0.19748133 0.19075248]]
[[0.         1.         0.        ]
 [0.33333333 0.33333333 0.33333333]]
value of table br policy [ 0.42101368 -0.42101368]
[[0.68208504 0.20399339 0.11392155]
 [0.33333333 0.33333333 0.33333333]]
value of hypernet br policy [ 0.03409839 -0.03409839]
[[0.68715835 0.20211504 0.11072652]
 [0.33333333 0.33333333 0.33333333]]
[[0.33333333 0.33333333 0.33333333]
 [0.         1.         0.        ]]
value of table br policy [-0.57643183  0.57643183]
[[0.33333333 0.33333333 0.33333333]
 [0.60787302 0.20392515 0.18820183]]
value of hypernet br policy [ 0.02928971 -0.02928971]
[[0.33333333 0.33333333 0.33333333]
 [0.61268049 0.20086195 0.18645754]]
[[0.         1.         0.        ]
 [0.33333333 0.33333333 0.33333333]]
value of table br policy [ 0.42622295 -0.42622295]
[[0.68432194 0.2048327  0.11084535]
 [0.33333333 0.33333333 0.33333333]]
value of hypernet br policy [ 0.03179898 -0.03179898]
[[0.68432194 0.2048327  0.11

 20%|█▉        | 19767/100000 [02:56<11:35, 115.38it/s]

[[0.33333333 0.33333333 0.33333333]
 [0.61026716 0.18761644 0.20211643]]
[[0.         1.         0.        ]
 [0.33333333 0.33333333 0.33333333]]
value of table br policy [ 0.40815073 -0.40815073]
[[0.67471904 0.21467647 0.1106045 ]
 [0.33333333 0.33333333 0.33333333]]
value of hypernet br policy [ 0.05065671 -0.05065671]
[[0.67131919 0.21740881 0.11127196]
 [0.33333333 0.33333333 0.33333333]]
[[0.33333333 0.33333333 0.33333333]
 [0.         1.         0.        ]]
value of table br policy [-0.56004723  0.56004723]
[[0.33333333 0.33333333 0.33333333]
 [0.61037123 0.1852238  0.20440494]]
value of hypernet br policy [ 0.05383032 -0.05383032]
[[0.33333333 0.33333333 0.33333333]
 [0.60496289 0.18902238 0.20601478]]
[[0.         1.         0.        ]
 [0.33333333 0.33333333 0.33333333]]
value of table br policy [ 0.3989481 -0.3989481]
[[0.67341399 0.21312337 0.11346266]
 [0.33333333 0.33333333 0.33333333]]
value of hypernet br policy [ 0.04927437 -0.04927437]
[[0.67341399 0.21312337 0.1134

 20%|██        | 20007/100000 [02:59<13:24, 99.44it/s] 

[[0.33333333 0.33333333 0.33333333]
 [0.60042876 0.20764203 0.19192919]]
[[0.         1.         0.        ]
 [0.33333333 0.33333333 0.33333333]]
value of table br policy [ 0.40849957 -0.40849957]
[[0.68373919 0.20120779 0.11505305]
 [0.33333333 0.33333333 0.33333333]]
value of hypernet br policy [ 0.0262585 -0.0262585]
[[0.68501079 0.201186   0.11380313]
 [0.33333333 0.33333333 0.33333333]]
[[0.33333333 0.33333333 0.33333333]
 [0.         1.         0.        ]]
value of table br policy [-0.57120766  0.57120766]
[[0.33333333 0.33333333 0.33333333]
 [0.5990057  0.20924628 0.19174796]]
value of hypernet br policy [ 0.02559218 -0.02559218]
[[0.33333333 0.33333333 0.33333333]
 [0.60016334 0.20805824 0.19177841]]
[[0.         1.         0.        ]
 [0.33333333 0.33333333 0.33333333]]
value of table br policy [ 0.40838493 -0.40838493]
[[0.68405205 0.20185252 0.11409547]
 [0.33333333 0.33333333 0.33333333]]
value of hypernet br policy [ 0.02655986 -0.02655986]
[[0.68405205 0.20185252 0.1140

 20%|██        | 20041/100000 [05:05<20:19, 65.57it/s]


KeyboardInterrupt: 

In [ ]:
ind = -1
nn_config
game
input_nets[0]

In [ ]:
# nn_policy = neural_policies.create_policy_net(game, nn_config)
ind = ind + 1
nn_player = 1
nn_policy = input_nets[ind]
nn_tab_policy = neural_policies.nn_to_tabular_policy(game, nn_policy, nn_player)
# br_pol = main.tabular_br(game, 1-nn_player, nn_tab_policy)
print(nn_tab_policy.action_probability_array)

# main.policy_gradient_br(
#     game, nn_config, reinforce_config, nn_player, nn_policy, nn_tab_policy
# )

br = main.compute_best_response_tabular_policy(game, nn_tab_policy, 1-nn_player)
print(br.action_probability_array)
policies = [nn_tab_policy, br] if nn_player == 0 else [br, nn_tab_policy]
combined_policy = main.combine_tabular_policies(game, *policies)
print("value of table br policy", main.policy_value(game, combined_policy))

nn_br = neural_policies.nn_to_tabular_policy(game, policy_nets[1-nn_player], 1-nn_player, nn_policy)
print(nn_br.action_probability_array)
policies = [nn_tab_policy, nn_br] if nn_player == 0 else [nn_br, nn_tab_policy]
combined_policy = main.combine_tabular_policies(game, *policies)
print("value of hypernet br policy", main.policy_value(game, combined_policy))

In [ ]:
pnout = policy_nets[1].model_output(input_nets[ind])
[print(x) for x in pnout.parameters()]

In [ ]:
pnout
game.information_state_tensor_shape()

In [ ]:
g2 = pyspiel.load_game("leduc_poker")
g2.information_state_tensor_shape()
s = game.new_initial_state()
s.information_state_tensor(1)

# test setting weights

In [ ]:
import neural_policies
importlib.reload(neural_policies)
import torch.nn as nn

In [ ]:
mlp = neural_policies.create_policy_net(game, nn_config)

In [ ]:
new_weights = torch.ones_like(mlp.get_weights(), requires_grad=True)

In [ ]:
new_weights.requires_grad, new_weights.grad

In [ ]:
mlp.set_weights(new_weights)

In [ ]:
mlp.network[0].weight.grad

In [ ]:
res = mlp.forward(torch.zeros(1))

In [ ]:
loss = res.sum()
loss.backward()

In [ ]:
mlp.network[0].weight.grad

In [ ]:
new_weights.grad

In [ ]:
linear = nn.Linear(2, 2)
linear.weight.grad

In [ ]:
new_weights = torch.ones(8, requires_grad=True)
# linear.weight = nn.Parameter(new_weights)
linear.weight.requires_grad = False
linear.weight.copy_(new_weights[:4].view(linear.weight.shape))

In [ ]:
inp = torch.ones(2, requires_grad=True)
loss = linear(inp).sum()

In [ ]:
loss.backward()

In [ ]:
inp.grad
linear.weight.grad

In [ ]:
new_weights.grad